// Stub for tsc — real file generated by `npx convex dev` when host mounts this component.
// Provides typed `api`, `internal`, and `components` references for this component's functions.
import type { FunctionReference } from "convex/server";

// ragSync internal schedulable functions (action | mutation, internal)
interface RagSyncInternal {
  addRagEntry: FunctionReference<"action" | "mutation", "internal">;
  markRagEntrySuperseded: FunctionReference<"action" | "mutation", "internal">;
}

// fixPatterns public query
interface FixPatternsApi {
  get: FunctionReference<"query", "public">;
}

export declare const api: {
  fixPatterns: FixPatternsApi;
};

export declare const internal: {
  ragSync: RagSyncInternal;
};

// RAG component shape (used by searchV1.ts via components.rag)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const components: Record<string, any>;
