#!/usr/bin/env python3
r"""enforce-no-claude-trailer — PreToolUse(Bash) Claude Code hook.

DESIGN REVISION v1.1.0 — predicate + scope inversion.
------------------------------------------------------
VERSION HONESTY (read before trusting any number here). This docstring labels a
DESIGN revision (`v1.1.0 — predicate + scope inversion`). It is NOT the VR
`contentVersion`. The VR `contentVersion` is an INDEPENDENT backend patch
counter incremented automatically by `bumpPatch` on any byte change — we cannot
set it, and it has read `1.0.2` while an older docstring lied `v1.0.3`. Do not
compare the two. The CANONICAL IDENTITY of this file is its `contentHash`
(SHA-256 of the exact bytes). RULE #30 conformance (sha256(local) == VR
contentHash) MUST be checked on the HASH, never on the version field. The
version string in this docstring is a human-facing design label only.

WHAT v1.1.0 CHANGES (two-axis fix). For six versions the SCOPE axis (which
invocation forms are covered) was hardened while the PREDICATE axis (what counts
as attribution) never moved — `VIOLATION_PATTERNS` was three enumerated regexes,
frozen since v1.0.0. The fail-closed inversion had been applied only to the
invocation-form axis; the attribution-form axis stayed fail-OPEN, so
`Generated by Claude Code` LEAKED while `Generated with Claude Code` blocked —
one word apart, same attribution. v1.1.0 inverts the posture on BOTH axes:

  PREDICATE (attribution axis) — now a FAMILY PREDICATE, not an enumeration.
  A single case-insensitive regex recognises the attribution FAMILY:
      family-verb  +  MANDATORY preposition  +  Claude/Anthropic (short window).
  The mandatory preposition (`by|with|via|using`) is what separates a
  well-formed attribution family from a catch-all: `created Anthropic client`
  (family verb, NO preposition) is ordinary prose and must NOT match, whereas
  `created by Claude` (verb + preposition + entity) is attribution and MUST.
  Requiring the preposition lets the predicate be broad on verbs and phrasings
  without swallowing every sentence that merely names a verb near "Anthropic".
  A separate `anthropic\.com` domain pattern stays as its own list entry.

  SCOPE (invocation axis) — commit-authoring git subcommands now ALL in scope.
  `git merge --no-ff -m`, `git merge -F <file>`, `git tag -a -m`, `git revert`,
  `git cherry-pick`, `git rebase` (and `git am`) each CREATE A COMMIT OBJECT
  whose message can carry the trailer. They are therefore in scope exactly like
  `git commit`: both the backstop and the precise tokenizer accept any of
  {commit, merge, tag, revert, cherry-pick, rebase, am} as the authoring
  subcommand, and `-F`/`--file`/`--body-file` are read for all of them.
  DELIBERATELY OUT OF SCOPE: `gh pr comment --body <...>`. A PR comment is NOT
  authorship of a commit object — reviewers legitimately POST verdicts that
  QUOTE the trailer ("this commit still carries Co-Authored-By: Claude"). Guard
  a comment and you block the review that catches the leak. This omission is a
  written decision, not an oversight.

v1.0.3 (fail-closed backstop + precise path). Enumerating shell invocation
forms is unwinnable — this guard leaked eleven times across four versions, each
fix adding one more recognised wrapper (`eval`, `bash -c`, backticks, `xargs`,
`find -exec`, `ssh`, aliases, `$'...'`, base64, …) only for the next probe to
find another. The design is therefore inverted: **a guard must block when it
does not understand, not pass.**

Two-layer scope detection now runs on the continuation-normalized raw command:

  1. Precise tokenizer path (unchanged) — accurate scope, drives the stderr
     report (which subcommand, which file).
  2. Fail-closed backstop (`_backstop_covered`) — the core of v1.0.3. If the
     whole words `git` AND `commit` both appear, OR `gh` AND `pr` AND one of
     `create|edit|merge` all appear, the command is treated as COVERED
     **regardless of invocation form**. Whatever wrapper hides the call
     (`eval`, backticks, `bash -c`, `sh -c`, `xargs`, `ssh host "…"`, line
     continuations), the words `git`+`commit` and the Anthropic trailer are all
     still present in the raw command text, so the backstop sees them.

  `is_covered_command()` = precise-path-any-segment OR backstop.

Line continuations (`\\` immediately followed by a newline) are normalised to a
single space FIRST — before any segment splitting — but only when NOT inside
single/double quotes. This is required because v1.0.2 made `\n` a segment
separator: without this normalisation a `git \<newline> commit` would fragment
into two segments and slip past the precise path (the exact regression that
manufactured the v1.0.2 leak).

DELIBERATE TRADE-OFF (fail-closed). The backstop may block a command that
merely MENTIONS both words together with a trailer, e.g.
`git log --grep "commit … Co-Authored-By: Claude"`. That is intentional: the
documented override `// allow-claude-trailer: <reason ≥ 6 chars>` is the escape
hatch for the rare verbatim-history case. Blocking a benign mention is cheap;
letting an attribution trailer through is the failure we are eliminating.

ACCEPTED FALSE-POSITIVE CLASS (named). Any command that SEARCHES for the
trailer — the trailer-audit / forensic tooling used to FIND offending commits —
is blocked by the backstop, because the words `git`/`commit` and the trailer
co-occur in the command text (the backstop cannot tell "writes the trailer"
from "greps for the trailer"). Two real examples:

    gh api repos/$R/commits/$sha -q .commit.message \
        | grep -c 'Co-Authored-By: Claude' ; git log --oneline
    git log --grep "commit Co-Authored-By: Claude"

This is accepted, not a defect: the auditor appends the canonical override
reason `// allow-claude-trailer: audit forensique du trailer` (any reason ≥ 6
chars works; this one is self-documenting). The stderr block message names this
class and prints the copy-pasteable line so an auditor is never tempted to
disarm the hook. NOTE: an audit command that does NOT contain the word `commit`
(e.g. `git log -1 --format='%B' $sha | grep -ci 'Co-Authored-By: Claude'`) is
not covered by the backstop at all, so it passes without any override.

RESIDUAL BOUNDARY (honest). The hook sees ONLY the Bash command STRING. A
trailer that is materialised entirely at runtime — read from a file the hook
cannot see, fetched over the network, decoded from an opaque blob, or produced
by a program's output — is out of scope by construction. The backstop closes
the *wrapper/quoting* class (the words are in the command text); it cannot close
the *runtime-materialisation* class (the words are not in the command text).

v1.0.2 (head/separator hardening): segment splitting now also breaks on a
**newline** (`\n`), a bare `&`, and subshell parens `(` / `)` — multi-line Bash
commands (the norm in this harness) and backgrounded/subshelled git commits no
longer slip past the per-segment scope check. Head normalisation now runs
`_strip_command_prefixes`, which loops past leading `VAR=value` assignments,
shell keywords (`if then else … fi do done while … { } ! ( )`) and wrapper
commands with their own options (`env`, `sudo`, `command`, `time`, `nohup`,
`exec`, `builtin`, `nice`, `ionice`, `stdbuf`) before deciding `prog`. This
closes the newline/keyword/`env …`/`sudo …`/`command …`/`time …`/`nohup …`
bypasses. shlex → ValueError → regex fallback preserved for heredocs.

v1.0.2: scope detection is now **tokenizer-based** (shlex), not raw-string regex.
The command is split into segments on shell separators (`&&`, `||`, `;`, `|`),
each segment is tokenized with `shlex.split`, and global git options (with or
without separate values, including quoted paths containing spaces) are walked
token-by-token to find the real subcommand. This closes the quoted-path bypass
(`git -C "dir with space" commit ...`) that any raw-string regex leaves open.
On a shlex `ValueError` (unbalanced quotes / heredocs) the segment falls back to
the v1.0.1 regex behaviour so heredoc coverage (`git commit -F - <<EOF`) stays.

v1.0.1: global git options (`-C <dir>`, `--no-pager`, `-c k=v`) placed between
`git` and `commit` are now inside the guarded scope (previously escaped the guard).

SCOPE
    Refuses any Anthropic/Claude attribution in git commits and GitHub PR
    authoring commands. Doctrine (Laurent, Day 123): no Anthropic/Claude
    attribution anywhere — commits, PR bodies, docs, code comments.

    Reads a JSON payload on stdin of the shape:
        {"tool_name": "Bash", "tool_input": {"command": "<shell command>"}}

    Covered commands (all AUTHOR a commit object whose message can carry the
    trailer, or a PR body that can):
        - git commit / merge / tag / revert / cherry-pick / rebase / am
          (message via -m "...", heredoc `-F - <<EOF`, or -F/--file/--body-file <file>)
        - gh pr create / gh pr edit / gh pr merge  (--body, -b, --body-file, --subject)

    Deliberately NOT covered (written decision, not an oversight):
        - gh pr comment  — a comment is not authorship; reviewers post verdicts
          that QUOTE the trailer, and guarding the comment blocks the review.

    Violation predicate (four precise shapes, case-insensitive) — NORMALIZE-THEN-
    MATCH. The scan text is first lowercased and every run of whitespace
    (including newlines), underscores and hyphens is collapsed to a single space
    (`_normalize_for_predicate`), so spelling/separator variants converge to one
    canonical form BEFORE matching. The predicate is FOUR precise shapes, not one
    loose window:
        1. TRAILER-KEY   — <family-verb>by: <window> Claude/Anthropic.
           family-verb stem = co-authored | signed-off | assisted | generated
                              | authored | written | created | made.
           No word boundary between the verb stem and `by` — this is what closes
           the glued `coauthoredby:` leak (normalization COLLAPSES separators, it
           never INSERTS one, so a `\b…by` could not match a run-together key).
           e.g. "Co-Authored-By: Claude", "Co_Authored_By: Claude",
                "CoAuthoredBy: Claude", "Co-Authored-By : Claude",
                "Assisted-By: Claude Opus 4.8", "Signed-off-by: Claude".
        2. FOOTER-PHRASE — <verb> <connector> (article/bracket?) Claude/Anthropic,
           the entity IMMEDIATELY adjacent to the connector.
           e.g. "Generated by Claude Code", "Made with Claude Code",
                "Generated via Claude", "Powered by Claude",
                "assisted by Anthropic".
        3. ON-BEHALF-OF  — "on behalf of ... Claude/Anthropic" (entity immediate).
        4. DOMAIN        — anthropic.com (separate load-bearing pattern, matched
           on both raw and normalized text).

    THE PRECISION DECISION — agent-adjacency (deliberate trade-off, written down).
        The retired predicate was `verb + connector + <anything within 40 chars>
        + entity`. It never required the entity to be the AGENT of the connector,
        so it fired FALSE POSITIVES on ordinary commit messages:
            "auto-generated by script for Anthropic API"  (agent = script)
            "generated by CI, references Anthropic client" (agent = CI)
            "file created by fixture, mocks Anthropic"     (agent = fixture)
        In each, the true agent of the connector is `script`/`CI`/`fixture`;
        `Anthropic` is merely a later word. Shapes 2 and 3 now REQUIRE the entity
        to be the agent of the connector — adjacent, modulo one article/bracket.
        CONSEQUENCE, accepted on purpose: a contrived prose form such as
            "Generated by the model known as Claude"
        is NO LONGER blocked (the token after the connector is `the model`, not
        the entity). This is a deliberate EXCHANGE: blocking `generated by CI`
        daily would get the hook disarmed, and a disarmed guard is worse than no
        guard because people still believe they are protected — the same argument
        the reviewer used about trailer-audit tooling, now turned toward
        precision. The trailer-key form (Shape 1) is the shape every REAL
        attribution trailer takes; the footer-phrase form (Shape 2) covers the
        marketing footer. Both are covered; distant-prose attribution is out of
        scope AND written down here.

    NAMED-ENTITY BOUNDARY (deliberate, architect-decided). The predicate fires
        ONLY on the NAMED entities `Claude` / `Anthropic` (and the `anthropic.com`
        domain). An UNNAMED reference to the authoring agent — "the model", "the
        assistant", "an AI" — is OUT of scope on purpose. The Day-123 doctrine
        forbids *nominative* attribution to a named third party (Anthropic/Claude):
        the harm is the gratuitous promotion of a NAMED brand. "Generated by the
        assistant" / "Co-Authored-By: an AI" attributes the work to nobody in
        particular — no named third party is promoted — so there is nothing for
        the doctrine to guard. Covering the unnamed case would require an
        open-ended semantic predicate ("does this phrase refer to some AI?"),
        which would fire FALSE POSITIVES on ordinary text ("the assistant manager
        approved", "an AI startup we integrate"). THE BOUNDARY IS THE NAMED
        ENTITY. This sits alongside the other two written boundaries above: the
        distant-prose attribution trade-off (agent-adjacency), and the
        runtime-materialised trailer the hook never sees (RESIDUAL BOUNDARY).

    Two DELIBERATE scope decisions (documented, not accidental):
        - "signed off": a `Signed-off-by: Claude` trailer ascribes authorship/
          endorsement of the commit to Claude exactly as `Co-Authored-By:` does
          (a DCO sign-off naming Claude is attribution) — in scope on purpose.
        - "on behalf of": "on behalf of Anthropic" is an attribution phrase
          (ascribes the work to Anthropic) with no single family verb — in
          scope on purpose, as a distinct grammatical form.

    NON-matches (intentional): "integrate Anthropic API client" (no verb),
        "created Anthropic client wrapper" (verb but NO adjacent connector+entity),
        "written approval from Anthropic legal" (connector `from` not in set),
        "generated by script for Anthropic API" (agent is `script`, not Claude).

OVERRIDE
    Add the marker `// allow-claude-trailer: <reason>` to the command, where
    <reason> is >= 6 characters (reserved for quoting history verbatim).
    A marker with a too-short or absent reason does NOT bypass.

EXIT CODES — three modes, and why the last two must NOT be conflated.
    A guard that does not block MUST say why — otherwise you can never
    distinguish "nothing to flag" from "I could not look". This hook therefore
    has THREE observable modes, not two:

      1. BLOCKS (exit 2). Anthropic/Claude attribution detected in a covered
         command. Writes the full detailed report to stderr.

      2. ALLOWS NOMINALLY (exit 0, stderr SILENT). The normal, healthy case:
         the command is out of scope, or it is covered but carries no
         attribution, or a valid override is present. Nothing to say — the
         guard looked and found nothing. Silence here is correct.

      3. ALLOWS BECAUSE IT COULD NOT LOOK (exit 0, ANNOUNCED on stderr). The
         guard failed OPEN before it could evaluate the command: stdin was
         unreadable, the payload was not valid JSON, the payload was not a JSON
         object, or an unexpected exception fired during evaluation. This is the
         mode that will actually occur in production the day a regex blows up or
         a `-F <file>` read raises something unforeseen. It emits ONE line to
         stderr via `_warn_fail_open(reason)`:
             enforce-no-claude-trailer: FAIL-OPEN (not checked) — <reason>. ...
         so a silent open is never mistaken for a clean pass.

    WHY MODES 2 AND 3 MUST STAY DISTINCT. Conflating "allowed nominally" with
    "allowed because I could not look" is the failure being avoided: a mute
    fail-open opens the guard without a word and nobody ever learns it opened.
    Mode 2 stays silent (nothing to flag); mode 3 announces itself (could not
    look). The exception path ADDITIONALLY logs a full traceback to
    /tmp/enforce-no-claude-trailer.errors.log — the stderr line is IN ADDITION
    to the log, not a replacement.

    EMPTY STDIN STAYS SILENT BY DESIGN. An empty / whitespace-only stdin is the
    harness's normal no-op invocation — there is genuinely nothing to check, so
    it is mode 2 (silent exit 0), NOT mode 3. Do not make it noisy.
"""

import json
import os
import re
import shlex
import sys
import traceback

ERROR_LOG = "/tmp/enforce-no-claude-trailer.errors.log"

# Normalization for the predicate ONLY (never used by scope detection, never by
# the override check — those must see the raw command text).
#
# NORMALIZE-THEN-MATCH is the structural fix for the separator/whitespace leak
# class. Every prior fix ENUMERATED separators and whitespace inside the regex
# (`co[-\s]?authored`, `[\s\-]*(?:by|with)`), which is an open-ended list: a
# newline between "by" and the entity, underscores instead of hyphens, or two
# spaces each require yet another alternative, and the next probe finds the one
# you missed. Instead we collapse the entire class BEFORE matching: lowercase,
# then squash every run of `[\s_\-]+` (whitespace INCLUDING newlines, plus
# underscores and hyphens) to a single space. `Co_Authored_By`,
# `Co-Authored-By`, `Generated<newline>by` and `Generated   by` all become the
# single canonical string `co authored by` / `generated by`. Spelling variants
# vanish BY CONSTRUCTION — the predicate never enumerates a separator again, so
# there is no "missed alternative" to leak through.
_NORMALIZE_SEP_RE = re.compile(r"[\s_\-]+")


def _normalize_for_predicate(text):
    """Lowercase + collapse every [\\s_\\-]+ run (incl. newlines) to one space.

    Used ONLY by the attribution predicate (contains_violation / _matched_
    pattern). Scope detection and the override check operate on the RAW command
    — normalization would destroy the flag/quoting structure they rely on.
    """
    if not text:
        return ""
    return _NORMALIZE_SEP_RE.sub(" ", text.lower())


# Load-bearing violation predicate (module-level list so the mutation-control
# test can still remove an entry and prove the guard does the work). Patterns
# run against the NORMALIZED text (see _normalize_for_predicate), so `.` safely
# spans former newlines/underscores/hyphens (they are now single spaces).
#
# v1.3.0 — AGENT-ADJACENCY, four precise shapes (replaces the single loose
# `verb + connector + .{0,40}? + entity` predicate that produced false positives).
# The retired predicate never required the entity to be the AGENT of the
# connector: `verb + connector + <anything within 40 chars> + entity` fired on
# `generated by CI, references Anthropic client` because `Anthropic` was merely a
# later word in the sentence — its true agent was `CI`. A guard that blocks
# routine work gets disarmed by the developer, and a disarmed guard is worse than
# no guard (people still believe they are protected). The four shapes below all
# require the entity to be the agent of the connector — adjacent, modulo an
# article/bracket — EXCEPT the trailer-key form, which anchors on a literal
# `<verb>by:` key (the shape every real attribution trailer takes).
#
# Shape 1 — TRAILER-KEY form (the dominant real shape). A key built from a family
#   verb + an optional connector-`by` + a colon, then the entity within a bounded
#   window: `Co-Authored-By: Claude`, `Signed-off-by: Claude`, `Assisted-By:
#   Claude Opus 4.8`. There is NO `\b` between the verb stem and `by` — that is
#   what closes the `coauthoredby:` (no-separator) leak: normalization collapses
#   separators but never INSERTS one, so `\bco ?authored\b by` could never match a
#   glued `coauthoredby`. Built as one alternation of verb stems + ` ?by\s*:`.
#
#   DELIBERATE SCOPE DECISION (signed off): a `Signed-off-by: Claude` DCO trailer
#   ascribes authorship/endorsement to Claude exactly as `Co-Authored-By:` — in
#   scope on purpose.
#
# Shape 2 — FOOTER-PHRASE form. The connector is IMMEDIATELY followed by the
#   entity (modulo one article/bracket): `Generated by Claude Code`, `Made with
#   Claude Code`, `Powered by Claude`, `assisted by Anthropic`. The immediacy is
#   the whole point — it is the AGENT-ADJACENCY property. `generated by script for
#   Anthropic API` does NOT match: the token right after the connector is
#   `script`, so `Anthropic` is not the agent.
#
# Shape 3 — ON-BEHALF-OF form: `on behalf of ... Claude/Anthropic`, entity
#   immediate (modulo `the`). A distinct grammatical attribution form.
#
# Shape 4 — anthropic.com DOMAIN, kept as its own separate entry so the
#   mutation-control test (which drops every pattern whose source mentions
#   "anthropic") can flip a domain case from block to allow. Run against BOTH raw
#   and normalized text (see contains_violation).
_TRAILER_VERB = (
    r"(?:co ?authored|signed ?off|assisted|generated"
    r"|authored|written|created|made)"
)
VIOLATION_PATTERNS = [
    # Shape 1 — trailer-key: <verb>by: <window> entity. No \b between verb & by.
    re.compile(
        r"\b" + _TRAILER_VERB + r" ?by\s*:.{0,40}?\b(?:claude|anthropic)\b",
        re.IGNORECASE,
    ),
    # Shape 2 — footer-phrase: connector immediately followed by the entity.
    re.compile(
        r"\b(?:generated|made|created|written|powered|assisted|authored)"
        r"\s+(?:by|with|via|using)\s+"
        r"(?:\[)?(?:the\s+|a\s+|an\s+)?(?:claude|anthropic)\b",
        re.IGNORECASE,
    ),
    # Shape 3 — on-behalf-of: entity immediate (modulo `the`).
    re.compile(
        r"\bon behalf of\s+(?:the\s+)?(?:claude|anthropic)\b",
        re.IGNORECASE,
    ),
    # Shape 4 — domain.
    re.compile(r"anthropic ?\. ?com", re.IGNORECASE),
]

OVERRIDE_RE = re.compile(r"//\s*allow-claude-trailer:\s*(\S.{5,})")

# git subcommands that author a commit object whose message can carry the
# trailer. Shared by the precise tokenizer, the regex fallback and the backstop.
GIT_AUTHORING_SUBCMDS = (
    "commit", "merge", "tag", "revert", "cherry-pick", "rebase", "am",
)
_GIT_SUB_ALT = "|".join(GIT_AUTHORING_SUBCMDS)

COVERED_GIT = re.compile(
    r"\bgit\b(?:\s+-[^\s]+(?:\s+[^\s-][^\s]*)?)*\s+(?:" + _GIT_SUB_ALT + r")\b"
)
COVERED_GH = re.compile(r"\bgh\s+pr\s+(?:create|edit|merge)\b")

# git global options that consume a SEPARATE next token as their value.
GIT_VALUE_OPTS = {
    "-C", "-c", "--git-dir", "--work-tree", "--namespace",
    "--exec-path", "--config-env",
}

# Shell segment separators (split scope per-segment so `cd /x && git ... commit`
# is evaluated on the git segment). Includes newline, bare `&`, subshell
# parens and backticks so multi-line, backgrounded/subshelled and
# backtick-substituted commits are each evaluated. Splitting is quote-aware
# (see `_split_segments`) so newlines *inside* a quoted commit message do not
# fragment the git segment.
SEGMENT_SPLIT_CHARS = set(";|&\n()`")

# Backstop word-boundary probes (case-sensitive). See _backstop_covered.
_BACKSTOP_GIT = re.compile(r"\bgit\b")
# Any authoring subcommand word co-occurring with `git` closes the backstop.
_BACKSTOP_GIT_SUB = re.compile(r"\b(?:" + _GIT_SUB_ALT + r")\b")
_BACKSTOP_GH = re.compile(r"\bgh\b")
_BACKSTOP_PR = re.compile(r"\bpr\b")
_BACKSTOP_GH_VERB = re.compile(r"\bcreate\b|\bedit\b|\bmerge\b")


def _normalize_continuations(command):
    """Collapse backslash-newline line continuations to a single space.

    Only outside single/double quotes — a `\\<newline>` inside a quoted commit
    message is left intact. Runs BEFORE segment splitting so a
    `git \\<newline> commit` is not fragmented by the newline separator (v1.0.2
    made `\n` a separator; without this it would manufacture a false negative).
    """
    if not command or "\\" not in command:
        return command
    out = []
    quote = None  # None | "'" | '"'
    i = 0
    n = len(command)
    while i < n:
        ch = command[i]
        if quote:
            out.append(ch)
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in ("'", '"'):
            quote = ch
            out.append(ch)
            i += 1
            continue
        if ch == "\\" and i + 1 < n and command[i + 1] == "\n":
            out.append(" ")
            i += 2
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def _backstop_covered(command):
    """Fail-closed backstop on the continuation-normalized raw command.

    True if the whole word `git` appears together with any commit-authoring
    subcommand word (commit|merge|tag|revert|cherry-pick|rebase|am), OR `gh` AND
    `pr` AND one of `create|edit|merge` all appear. Case-sensitive word-boundary
    search. Rationale: whatever wrapper hides the invocation (`eval`, backticks,
    `bash -c`, `xargs`, `ssh host "…"`, continuations), the words are all still
    present in the raw command text, so an attribution trailer cannot slip
    through an unrecognised form.
    """
    if not command:
        return False
    if _BACKSTOP_GIT.search(command) and _BACKSTOP_GIT_SUB.search(command):
        return True
    if (
        _BACKSTOP_GH.search(command)
        and _BACKSTOP_PR.search(command)
        and _BACKSTOP_GH_VERB.search(command)
    ):
        return True
    return False


def _split_segments(command):
    """Quote-aware split of a command into scope segments.

    Splits on `;`, `|`, `&`, newline and subshell parens `(`/`)` — but only
    when NOT inside single/double quotes, so a newline within a quoted commit
    message keeps the git segment intact. `&&`/`||` collapse naturally (empty
    middle segment is dropped by the caller)."""
    segments = []
    buf = []
    quote = None  # None | "'" | '"'
    for ch in command:
        if quote:
            buf.append(ch)
            if ch == quote:
                quote = None
            continue
        if ch in ("'", '"'):
            quote = ch
            buf.append(ch)
            continue
        if ch in SEGMENT_SPLIT_CHARS:
            segments.append("".join(buf))
            buf = []
            continue
        buf.append(ch)
    segments.append("".join(buf))
    return segments

# Shell keywords that can lead a command position (dropped during head strip).
SHELL_KEYWORDS = {
    "if", "then", "else", "elif", "fi", "do", "done", "while", "until",
    "for", "case", "esac", "function", "{", "}", "!", "(", ")",
}

# Wrapper commands: drop the wrapper + its own options, then re-evaluate head.
WRAPPER_COMMANDS = {
    "env", "sudo", "command", "time", "nohup", "exec", "builtin",
    "nice", "ionice", "stdbuf", "xargs",
}

# Wrapper flags that consume a following separate value token.
WRAPPER_VALUE_FLAGS = {"-u", "-I", "-n", "-P", "-d"}


def _strip_command_prefixes(tokens):
    """Drop leading assignments, shell keywords and wrapper commands.

    Loops until the head token is a real program (or tokens exhausted),
    returning the remaining argv whose head is the program to inspect.
    """
    toks = list(tokens)
    while toks:
        head = toks[0]

        # leading VAR=value assignment
        if re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", head):
            toks.pop(0)
            continue

        # leading shell keyword / bare brace / paren
        if head in SHELL_KEYWORDS:
            toks.pop(0)
            continue

        # leading wrapper command
        if os.path.basename(head) in WRAPPER_COMMANDS:
            wrapper = os.path.basename(head)
            toks.pop(0)  # drop the wrapper token itself
            # drop the wrapper's own following tokens
            while toks:
                nxt = toks[0]
                if wrapper == "env" and re.match(
                    r"^[A-Za-z_][A-Za-z0-9_]*=", nxt
                ):
                    toks.pop(0)  # env VAR=value
                    continue
                if nxt.startswith("-"):
                    # value-taking flags consume the next token
                    if nxt in WRAPPER_VALUE_FLAGS and len(toks) > 1:
                        toks.pop(0)
                        toks.pop(0)
                    else:
                        toks.pop(0)
                    continue
                break
            continue

        # head is a real program
        break
    return toks


def _segment_covered_regex(segment):
    """v1.0.1 raw-string regex fallback (used when shlex cannot tokenize)."""
    return bool(COVERED_GIT.search(segment) or COVERED_GH.search(segment))


def _tokens_covered(tokens):
    """True if tokenized argv is a covered git authoring subcommand
    (commit|merge|tag|revert|cherry-pick|rebase|am) or
    gh-pr-{create,edit,merge}."""
    # Normalise the head: drop leading assignments, shell keywords and wrappers.
    tokens = _strip_command_prefixes(tokens)
    if not tokens:
        return False

    prog = os.path.basename(tokens[0])
    args = tokens[1:]

    if prog == "git":
        i = 0
        while i < len(args):
            tok = args[i]
            if tok in GIT_VALUE_OPTS:
                i += 2  # skip option AND its separate value
                continue
            if tok.startswith("-"):
                i += 1  # skip lone option (incl. --git-dir=/x, -c k=v inline, --no-pager)
                continue
            return tok in GIT_AUTHORING_SUBCMDS  # first non-option = subcommand
        return False

    if prog == "gh":
        non_opts = []
        i = 0
        while i < len(args) and len(non_opts) < 2:
            tok = args[i]
            if tok.startswith("-"):
                i += 1
                continue
            non_opts.append(tok)
            i += 1
        return (
            len(non_opts) >= 2
            and non_opts[0] == "pr"
            and non_opts[1] in ("create", "edit", "merge")
        )

    return False


def _tokens_covered_any_segment(command):
    """Precise tokenizer path. True if ANY segment is a covered command."""
    if not command:
        return False
    for segment in _split_segments(command):
        segment = segment.strip()
        if not segment:
            continue
        try:
            tokens = shlex.split(segment, comments=False)
        except ValueError:
            # Unbalanced quotes / heredoc — preserve v1.0.1 regex coverage.
            if _segment_covered_regex(segment):
                return True
            continue
        if not tokens:
            continue
        if _tokens_covered(tokens):
            return True
    return False


def is_covered_command(command):
    """Scope detection: precise tokenizer path OR fail-closed backstop.

    Runs on the continuation-normalized command so a `git \\<newline> commit`
    is not fragmented. The precise path stays for accurate stderr reporting; the
    backstop guarantees no unrecognised invocation form slips through.
    """
    if not command:
        return False
    normalized = _normalize_continuations(command)
    return (
        _tokens_covered_any_segment(normalized)
        or _backstop_covered(normalized)
    )


def _log_error():
    try:
        with open(ERROR_LOG, "a") as fh:
            fh.write(traceback.format_exc())
    except Exception:
        pass


def _warn_fail_open(reason):
    """Announce a NON-nominal fail-open on stderr (mode 3 of the three modes).

    Writes exactly ONE line so a silent open is never mistaken for a clean pass.
    Best-effort: never raises from inside (a failure to warn must not itself
    crash the user's shell). This is IN ADDITION to `_log_error()` — it does not
    replace the traceback log.
    """
    try:
        sys.stderr.write(
            f"enforce-no-claude-trailer: FAIL-OPEN (not checked) — {reason}. "
            "The command was ALLOWED without an attribution check.\n"
        )
    except Exception:
        pass


def has_override(command):
    """True if a valid override marker (reason >= 6 chars) is present."""
    m = OVERRIDE_RE.search(command)
    if not m:
        return False
    return len(m.group(1).strip()) >= 6


def contains_violation(text):
    if not text:
        return False
    normalized = _normalize_for_predicate(text)
    for pat in VIOLATION_PATTERNS:
        # Predicate runs on the normalized text (separators collapsed). The
        # domain pattern also runs on the raw text so a normalization-adjacent
        # edge cannot hide `anthropic.com`.
        if pat.search(normalized) or pat.search(text):
            return True
    return False


def _read_file_safe(path):
    """Read a file's content; return "" on any error (fail-safe)."""
    try:
        with open(path, "r", errors="replace") as fh:
            return fh.read()
    except Exception:
        return ""


def _extract_flag_files(tokens):
    """Yield file paths referenced by -F/--file/--body-file flags."""
    file_flags = {"-F", "--file", "--body-file"}
    for i, tok in enumerate(tokens):
        if tok in file_flags and i + 1 < len(tokens):
            nxt = tokens[i + 1]
            if nxt != "-":  # `-F -` means heredoc/stdin, not a file
                yield nxt
        else:
            for flag in ("--file=", "--body-file="):
                if tok.startswith(flag):
                    yield tok[len(flag):]


def gather_scan_text(command):
    """Collect all text that should be scanned for a covered command.

    Includes the raw command (covers inline -m, heredoc bodies, --body/-b/
    --subject inline values) plus the content of any referenced files.
    """
    parts = [command]

    # Try to tokenize to find file-flag arguments. shlex may fail on heredocs;
    # fall back to a regex sweep for file flags in that case.
    try:
        tokens = shlex.split(command, comments=False)
    except ValueError:
        tokens = []

    file_paths = list(_extract_flag_files(tokens))
    if not file_paths:
        for m in re.finditer(r"(?:-F|--file|--body-file)[=\s]+(\S+)", command):
            arg = m.group(1)
            if arg != "-":
                file_paths.append(arg)

    for path in file_paths:
        content = _read_file_safe(path)
        if content:
            parts.append(content)

    return "\n".join(parts)


def evaluate_command(command):
    """Return the exit code (0 allow / 2 block) for a bash command."""
    if not command or not isinstance(command, str):
        return 0

    if not is_covered_command(command):
        return 0

    scan_text = gather_scan_text(command)
    if not contains_violation(scan_text):
        return 0

    # Violation present — honor a valid override, else block.
    if has_override(command):
        return 0

    return 2


def _matched_pattern(text):
    normalized = _normalize_for_predicate(text)
    for pat in VIOLATION_PATTERNS:
        if pat.search(normalized) or pat.search(text):
            return pat.pattern
    return "unknown"


def main():
    try:
        raw = sys.stdin.read()
    except Exception:
        _log_error()
        _warn_fail_open("stdin unreadable")
        return 0

    # Empty / whitespace-only stdin is the harness's normal no-op invocation —
    # nothing to check, so this is a NOMINAL silent allow (mode 2), NOT a
    # could-not-look fail-open. Keep it silent by design.
    if not raw or not raw.strip():
        return 0

    try:
        payload = json.loads(raw)
    except (ValueError, TypeError):
        _warn_fail_open("stdin is not valid JSON")
        return 0

    if not isinstance(payload, dict):
        _warn_fail_open("payload is not a JSON object")
        return 0

    try:
        command = payload.get("tool_input", {}).get("command", "")
        code = evaluate_command(command)
        if code == 2:
            matched = _matched_pattern(gather_scan_text(command))
            sys.stderr.write(
                "BLOCKED by enforce-no-claude-trailer: Anthropic/Claude "
                "attribution detected in a commit/PR authoring command.\n"
                f"  Matched pattern: {matched}\n"
                "  Doctrine (Day 123): no Anthropic/Claude attribution anywhere.\n"
                "  If you are WRITING a commit/PR: remove the Co-Authored-By / "
                "noreply@anthropic.com / 'Generated with Claude' trailer.\n"
                "  If you are AUDITING the trailer (a command that SEARCHES for "
                "it, e.g. `git log --grep`, `grep -c 'Co-Authored-By: Claude'`) "
                "or quoting history verbatim: this is an accepted false "
                "positive. Append the override to pass:\n"
                "    // allow-claude-trailer: audit forensique du trailer\n"
                "  Override accepts any reason >= 6 chars; the two legitimate "
                "classes are forensic audit of the trailer and quoting history "
                "verbatim.\n"
            )
        return code
    except Exception as exc:
        _log_error()
        _warn_fail_open(f"unexpected error: {type(exc).__name__}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
