import { v } from "convex/values";
import { internalMutation } from "./_generated/server";

// ─────────────────────────────────────────────────────────────────────────────
// seedClientOrgMapping — idempotent per-org row provisioning.
// ─────────────────────────────────────────────────────────────────────────────
//
// Creates AT MOST ONE `client_org_mapping` document per Clerk org slug. The
// `_id` is generated by Convex on first insert and never re-created or
// re-typed — it is the durable address that `tenantSlug` (convex/lib/
// tenantSlug.ts) derives its neutral slug from.
//
// internalMutation: not client-facing. Only callable server-to-server (e.g.
// `npx convex run tenantOrgSeed:seedClientOrgMapping` by an operator, or from
// another internal function) — never exposed to the dashboard/MCP client
// surface. This is the auth boundary for this function: it is unreachable
// from any authenticated-but-untrusted client call.
//
// IDEMPOTENCE CONTRACT (load-bearing): calling this twice with the same
// `clerkOrgSlug` MUST NOT create a second document and MUST NOT change the
// existing document's `_id`. An `_id` that moves is an address that moves —
// a silent client outage the next time this seed is replayed.
//
// This function does NOT touch `memories`, namespaces, or
// `oauth_scope_profiles`. It only ensures the destination address exists.
// Migrating data to that address is a separate, later task.

export const seedClientOrgMapping = internalMutation({
	args: {
		clerkOrgSlug: v.string(),
		displayName: v.string(),
		allowedOrchestrators: v.array(v.string()),
		scopes: v.array(v.string()),
	},
	returns: v.id("client_org_mapping"),
	handler: async (ctx, args) => {
		const existing = await ctx.db
			.query("client_org_mapping")
			.withIndex("by_clerk_slug", (q) =>
				q.eq("clerkOrgSlug", args.clerkOrgSlug),
			)
			.first();

		if (existing) {
			// Idempotent no-op: same _id, no second row, no mutation of fields.
			// (Field updates, if ever needed, are a distinct explicit mutation —
			// this seed's only job is "ensure the address exists exactly once".)
			return existing._id;
		}

		return await ctx.db.insert("client_org_mapping", {
			clerkOrgSlug: args.clerkOrgSlug,
			displayName: args.displayName,
			allowedOrchestrators: args.allowedOrchestrators,
			scopes: args.scopes,
			isActive: true,
			createdAt: Date.now(),
		});
	},
});
