/**
 * Day 92 C3 — B2 §4 description schema compliance test
 *
 * Every tool registered in tools.ts must satisfy:
 *   1. Name matches allowed-verb whitelist regex (§1)
 *   2. Description is between 80 and 500 characters (§4)
 *   3. Description contains "WHEN:" (§4 WHEN clause)
 *   4. Description contains "EXAMPLE:" (§4 example coverage, §3)
 *
 * Legacy aliases (non-standard verbs kept for backward compat) are allowed but
 * must be on the LEGACY_ALIASES whitelist — they still need B2-compliant descriptions.
 *
 * Mission k57a36y8w5t085bqr23dsmvb2d882506 — task k178d3nsyj5dhde1qyvncfvvn988307g
 * B2 PR #667 — A2 PR #661 — Pi auth token k17f493gw0cpbr3nxkvcc09ngn884n22
 */

import { describe, expect, it } from "vitest";

// ── B2 §1 allowed verb whitelist ─────────────────────────────────────────────

const ALLOWED_VERB_REGEX =
	/^(create|get|list|update|delete|search|send|check|store|recall|whoami|mark|register|link|complete|start|accept|settle|patch|revoke|checkout|block|pause|resume|verify|instantiate|hybrid_search|text_search|soft_delete|issue_stats|validate_task_payload)(_[a-z][a-z0-9_]*)?$/;

/**
 * Legacy aliases: original names that used non-standard verbs, kept for
 * backward compatibility with existing customer connectors.
 * Verified description compliance (B2 §4) applies to these too — they must
 * have WHEN + EXAMPLE even as aliases.
 */
const LEGACY_ALIASES = new Set([
	"add_repo_mapping",
	"remove_repo_mapping",
	"add_deployment",
	"remove_deployment",
	"validate_mandate_spending",
	"validate_fix",
	"add_fix_attempt",
	"add_task_dependency",
	"set_summary",
	"write_diary",
]);

// ── Tool registry (extracted from tools.ts registrations) ────────────────────
// Format: [name, description]
// Generated by auditing all server.tool() calls in mcp-server/src/tools.ts

const TOOL_REGISTRY: Array<[string, string]> = [
	[
		"store_memory",
		"Store a typed memory entry (user/feedback/project/reference) in VantagePeers with optional graph relations. WHEN: use after any decision, rule, or lesson that must persist across sessions. EXAMPLE: store_memory namespace='global' type='feedback' content='Alpha prefers concise replies' createdBy='beta'.",
	],
	[
		"soft_delete_memory",
		"Soft-delete a memory so it stops appearing in recall results while remaining in the audit log. WHEN: use to retire an outdated fact or superseded rule without permanent data loss. EXAMPLE: soft_delete_memory memoryId='j57dy3049btafda9m2f5d2ggk987ph3f'.",
	],
	[
		"get_memory",
		"Fetch a single memory by its Convex document ID, including relations and episode metadata. WHEN: use when you have a specific memoryId from a prior recall/store and need the full record. EXAMPLE: get_memory memoryId='j57dy3049btafda9m2f5d2ggk987ph3f'.",
	],
	[
		"recall",
		"Semantic vector search over VantagePeers memories, ranked by cosine similarity. WHEN: use at session start or before decisions — prefer over text_search for intent-based queries. EXAMPLE: recall query='Pi feedback rules' namespace='global' type='feedback' limit=20.",
	],
	[
		"text_search",
		"BM25 full-text keyword search over VantagePeers memories for exact term matching. WHEN: use when recall returns too-broad results and you need a specific exact phrase or ID. EXAMPLE: text_search query='Day 92 C3 descriptions' namespace='project/vantage-peers' limit=10.",
	],
	[
		"hybrid_search",
		"Combined vector + BM25 search via Reciprocal Rank Fusion for best semantic and keyword coverage. WHEN: use when neither recall nor text_search alone yields good results — highest recall quality. EXAMPLE: hybrid_search query='onboarding customer flow' namespace='project/vantage-peers' limit=20.",
	],
	[
		"store_episode",
		"Store a structured episodic memory capturing context, goal, action, outcome, and insight from a past event. WHEN: use after completing a non-trivial task or encountering an unexpected failure or success. EXAMPLE: store_episode namespace='orchestrator/alpha' createdBy='alpha' severity='major' context='...' goal='...' action='...' outcome='...' insight='...'.",
	],
	[
		"get_profile",
		"Fetch an orchestrator profile with static identity and dynamic session state fields. WHEN: use to check peer status, capabilities, or current task before assigning work. EXAMPLE: get_profile orchestratorId='gamma'.",
	],
	[
		"update_profile",
		"Create or update an orchestrator profile with static identity facts and dynamic session state. WHEN: call on each session start to update lastSeen/sessionCount, or when role/capabilities change. EXAMPLE: update_profile orchestratorId='alpha' dynamic={lastSeen: Date.now(), sessionCount: 5, currentTask: 'C3 descriptions'}.",
	],
	[
		"list_memories",
		"List active (isLatest=true) memories for a namespace, ordered newest first. WHEN: use to audit what a namespace contains or to paginate all entries without a query. EXAMPLE: list_memories namespace='project/vantage-peers' type='project' limit=20.",
	],
	[
		"send_message",
		"Send a message to one, many, or all orchestrators via channel routing (broadcast / role DM / instance DM). WHEN: use to notify peers of task completion, handoff, or decision; creates one receipt per recipient. EXAMPLE: send_message from='alpha' channel='beta' content='C3 descriptions PR ready for review'.",
	],
	[
		"check_messages",
		"Check for unread messages addressed to a recipient role, returning receiptIds for acknowledgment. WHEN: call at session start and after long pauses to drain the inbox before starting work. EXAMPLE: check_messages recipient='gamma' recipientInstanceId='gamma-vps'.",
	],
	[
		"mark_as_read",
		"Mark one or more message receipts as read using receiptIds from check_messages. WHEN: call immediately after processing each batch of messages returned by check_messages. EXAMPLE: mark_as_read receiptIds=['j57aaaaa...', 'j57bbbbb...'].",
	],
	[
		"delete_message",
		"Delete a message and all its receipts; only the original sender or system may delete. WHEN: use to retract a mistaken broadcast or sensitive content before recipients read it. EXAMPLE: delete_message messageId='j57dy3049btafda9m2f5d2ggk987ph3f' callerOrchestrator='alpha'.",
	],
	[
		"set_summary",
		"Update the current-work summary for an orchestrator instance, visible via list_peers. WHEN: call at the start of each session and after major context switches to keep peers informed. EXAMPLE: set_summary orchestratorId='alpha' instanceId='alpha-vps' summary='Standardizing 86 tool descriptions for B2 PR#667'.",
	],
	[
		"list_peers",
		"List all orchestrator profiles with current status, summary, and session info, newest first. WHEN: use before assigning work or sending a DM to confirm who is active and what they are doing. EXAMPLE: list_peers limit=20 fields='lite'.",
	],
	[
		"list_messages",
		"List historical messages filtered by session day or sender, newest first; use check_messages for unread. WHEN: use for audit, recap, or debugging a specific day's message traffic. EXAMPLE: list_messages sessionDay=92 from='alpha' limit=20.",
	],
	[
		"list_broadcast_status",
		"Show read/unread receipt status for a broadcast message by messageId. WHEN: use after send_message to confirm all recipients acknowledged a critical announcement. EXAMPLE: list_broadcast_status messageId='j57dy3049btafda9m2f5d2ggk987ph3f'.",
	],
	[
		"create_task",
		"Create a task assigned to an orchestrator with priority, status tracking, and optional mission link. WHEN: use to delegate work, track a deliverable, or instantiate a step from a mission plan. EXAMPLE: create_task title='Standardize tool descriptions' assignedTo='beta' priority='high' createdBy='alpha'.",
	],
	[
		"list_tasks",
		"List tasks with optional filters by assignee, status, project, or creator, newest first. WHEN: use to check the backlog, review in-progress items, or audit a specific project's tasks. EXAMPLE: list_tasks assignedTo='gamma' status='in_progress' project='vantage-peers' limit=20.",
	],
	[
		"update_task",
		"Update any mutable field on a task; only provided fields are patched, updatedAt auto-set. WHEN: use to reassign, reprioritize, or add context to an existing task without recreating it. EXAMPLE: update_task taskId='k178d3ns...' status='review' callerOrchestrator='alpha'.",
	],
	[
		"complete_task",
		"Mark a task as done with a mandatory completionNote; always notify the creator via send_message after. WHEN: call when all deliverables are committed or verified — never complete without a proof token in the note. EXAMPLE: complete_task taskId='k178d3ns...' completionNote='PR #667 merged, 86 descriptions updated' callerOrchestrator='beta'.",
	],
	[
		"start_task",
		"Set a task to in_progress and record the startedAt timestamp for duration tracking. WHEN: call as the first action when picking up a task to signal activity and enable metrics. EXAMPLE: start_task taskId='k178d3ns...' callerOrchestrator='gamma'.",
	],
	[
		"checkout_task",
		"Atomically claim a todo task, preventing race conditions when multiple orchestrators compete. WHEN: use before start_task in multi-orchestrator queues to ensure exclusive ownership. EXAMPLE: checkout_task taskId='k178d3ns...' callerOrchestrator='alpha' callerInstance='alpha-vps'.",
	],
	[
		"delete_task",
		"Permanently delete a task; only the creator or system role may delete. WHEN: use to remove erroneously created tasks or test artifacts — prefer complete_task for real work. EXAMPLE: delete_task taskId='k178d3ns...' callerOrchestrator='alpha'.",
	],
	[
		"block_task",
		"Mark a task as blocked with an optional reason and blocking task IDs, setting status to blocked. WHEN: use when external dependency or missing input prevents progress — record the specific blocker. EXAMPLE: block_task taskId='k178d3ns...' reason='Waiting for B2 PR#667 merge' callerOrchestrator='beta'.",
	],
	[
		"add_task_dependency",
		"Add dependency task IDs to a task so it cannot start until all listed tasks complete. WHEN: use when creating a task that depends on prior work not yet captured in dependsOn. EXAMPLE: create_task_dependency taskId='k178d3ns...' dependsOn=['k17bbbbb...'] callerOrchestrator='alpha'.",
	],
	[
		"list_tasks_by_mission",
		"List all tasks linked to a mission, optionally filtered by status, newest first. WHEN: use to review mission progress or find blocked/open tasks within a specific mission. EXAMPLE: list_tasks_by_mission missionId='k57a36y8...' status='in_progress' limit=20.",
	],
	[
		"create_mission",
		"Create a mission grouping related tasks under a project with a pilot orchestrator and agent list. WHEN: use when starting a multi-task initiative that needs lifecycle tracking and progress reporting. EXAMPLE: create_mission name='Day 92 C3 Descriptions' project='vantage-peers' pilot='alpha' agents=['beta','gamma'] priority='high' createdBy='alpha'.",
	],
	[
		"list_missions",
		"List missions filtered by project, pilot, or status, newest first with cursor paging support. WHEN: use to audit active missions, find missions by pilot, or check cross-project progress. EXAMPLE: list_missions project='vantage-peers' status='execute' pilot='alpha' limit=20.",
	],
	[
		"get_mission",
		"Fetch a single mission by Convex ID with full details: status, pilot, agents, progress, and dates. WHEN: use before assigning tasks or reporting to get the canonical mission state. EXAMPLE: get_mission missionId='k57a36y8w5t085bqr23dsmvb2d882506'.",
	],
	[
		"update_mission",
		"Update any mutable field on a mission; only provided fields are patched, updatedAt auto-set. WHEN: use to advance status, update progress percentage, or change pilot/agents mid-flight. EXAMPLE: update_mission missionId='k57a36y8...' progress=75 status='validate'.",
	],
	[
		"update_mission_status",
		"Change a mission's lifecycle status in a single call without touching other fields. WHEN: use as a lightweight alternative to update_mission when only the status changes. EXAMPLE: update_mission_status missionId='k57a36y8...' status='complete'.",
	],
	[
		"write_diary",
		"Write or upsert a diary entry for a specific date and orchestrator with highlights and blockers. WHEN: call at end of session to record what was accomplished, learned, and what blocked progress. EXAMPLE: create_diary date='2026-06-06' orchestrator='gamma' content='Standardized 86 descriptions...'.",
	],
	[
		"get_diary",
		"Fetch a diary entry for a specific date and orchestrator, returning null if none exists. WHEN: use to review what an orchestrator did on a given day for recap or handoff briefing. EXAMPLE: get_diary date='2026-06-06' orchestrator='alpha'.",
	],
	[
		"list_diaries",
		"List diary entries filtered by orchestrator or author, newest first with cursor paging support. WHEN: use to review recent history across sessions or audit a period of activity. EXAMPLE: list_diaries orchestrator='beta' limit=10 fields='lite'.",
	],
	[
		"create_briefing_note",
		"Create a structured briefing note capturing a topic discussion with participants, decisions, and memory links. WHEN: use after key architectural, product, or operational discussions to record decisions durably. EXAMPLE: create_briefing_note title='C3 desc standard' topic='architecture' participants=['alpha','beta'] content='...' createdBy='gamma'.",
	],
	[
		"update_briefing_note",
		"Update an existing briefing note; only provided fields are patched (arrays are FULL REPLACE). WHEN: use to add decisions, fix content, or relink memories — RBAC: caller must be createdBy or system. EXAMPLE: update_briefing_note noteId='j57aaaaa...' callerOrchestrator='alpha' decisions=['Use hybrid_search first'].",
	],
	[
		"get_briefing_note",
		"Fetch a single briefing note by ID with all fields: title, topic, participants, content, decisions, and links. WHEN: use when you have a specific noteId and need the full structured record for a handoff or recap. EXAMPLE: get_briefing_note noteId='j57dy3049btafda9m2f5d2ggk987ph3f'.",
	],
	[
		"list_briefing_notes",
		"List briefing notes filtered by topic, newest first, with cursor paging support. WHEN: use to review recent discussions on a topic or audit the full briefing history. EXAMPLE: list_briefing_notes topic='architecture' limit=10 fields='lite'.",
	],
	[
		"register_component",
		"Register or upsert a component (agent/skill/hook/plugin) in the VantagePeers registry by name+type. WHEN: use when publishing a new version of an agent skill or hook so peers can discover and use it. EXAMPLE: register_component name='check-tasks' type='skill' version='1.2.0' createdBy='alpha' content='...'.",
	],
	[
		"list_components",
		"List registered components filtered by type or team, newest first with cursor paging support. WHEN: use to discover available skills before building a workflow or to audit the registry. EXAMPLE: list_components type='skill' team='development' limit=20.",
	],
	[
		"get_component",
		"Fetch a single component by name and type, returning the full source content and metadata. WHEN: use before invoking a skill to read its interface, version, and implementation. EXAMPLE: get_component name='check-tasks' type='skill'.",
	],
	[
		"update_component",
		"Update a component's content, version, or team; only provided fields are patched. WHEN: use to bump a skill version or fix content without re-registering from scratch. EXAMPLE: update_component componentId='j57aaaaa...' version='1.3.0' content='...'.",
	],
	[
		"delete_component",
		"Permanently delete a component from the registry by Convex document ID. WHEN: use to remove deprecated or test components that should no longer be discoverable. EXAMPLE: delete_component componentId='j57aaaaa...'.",
	],
	[
		"search_components",
		"Search components by name or team substring with optional type filter. WHEN: use before register_component to check if a similar component already exists in the registry. EXAMPLE: search_components query='check-tasks' type='skill' limit=10.",
	],
	[
		"create_recurring_task",
		"Create a recurring task template that auto-generates tasks on a cron schedule. WHEN: use for daily standups, weekly reviews, or any repeating work item pattern. EXAMPLE: create_recurring_task title='Daily standup' assignedTo='alpha' priority='medium' cronExpression='0 9 * * *' createdBy='alpha'.",
	],
	[
		"list_recurring_tasks",
		"List recurring task templates filtered by assignee or active status, newest first. WHEN: use to audit which schedules are active or find templates to pause/resume/update. EXAMPLE: list_recurring_tasks assignedTo='beta' active=true limit=20.",
	],
	[
		"pause_recurring_task",
		"Pause a recurring task template to stop auto-creating tasks until explicitly resumed. WHEN: use during holidays, freezes, or when the assignee is unavailable for a period. EXAMPLE: pause_recurring_task taskId='j57aaaaa...'.",
	],
	[
		"resume_recurring_task",
		"Resume a paused recurring task template and recalculate its next scheduled run time. WHEN: use after a pause period ends to re-enable automatic task generation. EXAMPLE: resume_recurring_task taskId='j57aaaaa...'.",
	],
	[
		"delete_recurring_task",
		"Permanently delete a recurring task template, stopping all future scheduled task generation. WHEN: use when a recurring process is retired and should never generate tasks again. EXAMPLE: delete_recurring_task taskId='j57aaaaa...'.",
	],
	[
		"update_recurring_task",
		"Update a recurring task template's fields; cronExpression change auto-recalculates nextRunAt. WHEN: use to change assignee, schedule, or priority of an active recurring template. EXAMPLE: update_recurring_task recurringTaskId='j57aaaaa...' cronExpression='0 10 * * 1' priority='high'.",
	],
	[
		"create_mandate",
		"Create a cross-orchestrator service mandate with agreed token budget and spending limits. WHEN: use when one orchestrator commissions work from another with formal budget accountability. EXAMPLE: create_mandate requestedBy='alpha' fulfilledBy='beta' service='code review' budget=5000.",
	],
	[
		"accept_mandate",
		"Accept a mandate by the fulfilledBy orchestrator, advancing status from requested to accepted. WHEN: call when the fulfiller confirms they can deliver the service within the agreed budget. EXAMPLE: accept_mandate mandateId='j57aaaaa...' callerOrchestrator='beta'.",
	],
	[
		"update_mandate",
		"Update a mandate's status, tokensCost, or linkedTaskIds; only fulfilledBy or system may update. WHEN: use to record spend progress, link created tasks, or advance status to delivered. EXAMPLE: update_mandate mandateId='j57aaaaa...' callerOrchestrator='beta' tokensCost=1200 status='delivered'.",
	],
	[
		"settle_mandate",
		"Settle a mandate by confirming delivery and recording the final token cost; sets status to settled. WHEN: call after verifying the delivered work meets the mandate scope — closes the billing cycle. EXAMPLE: settle_mandate mandateId='j57aaaaa...' callerOrchestrator='alpha' finalCost=4800.",
	],
	[
		"validate_mandate_spending",
		"Check whether a proposed token spend is within a mandate's AP2 spending limits. WHEN: call before each service transaction to prevent over-spend and get within/exceeded status. EXAMPLE: check_mandate_spending mandateId='j57aaaaa...' proposedAmount=500.",
	],
	[
		"list_mandates",
		"List mandates filtered by requestedBy, fulfilledBy, or status, newest first with cursor paging. WHEN: use to audit active service agreements or track billing between orchestrator pairs. EXAMPLE: list_mandates requestedBy='alpha' status='in_progress' limit=20.",
	],
	[
		"create_bu",
		"Create a new business unit with strategy, business model, team composition, and KPIs. WHEN: use when launching a new revenue line or formalizing an existing product unit. EXAMPLE: create_bu name='VantagePeers' orchestratorId='alpha' status='building' purpose='...' businessModel='...' targetCustomers='...' services=['MCP'] pricing='...' revenueProjections={y1:0,y2:50000,y3:200000} coreTeam={agents:['alpha'],skills:[],hooks:[],plugins:[]} coreProcesses=['...'] dependencies=[] kpis=['ARR'].",
	],
	[
		"update_bu",
		"Update any mutable field on a business unit; only provided fields are patched, updatedAt auto-set. WHEN: use to update status, revenue projections, or team composition as the BU evolves. EXAMPLE: update_bu buId='j57aaaaa...' status='live' revenueProjections={y1:10000,y2:80000,y3:300000}.",
	],
	[
		"get_bu",
		"Fetch a single business unit by Convex document ID, returning null if not found. WHEN: use before updating or reporting on a BU to get the current canonical state. EXAMPLE: get_bu buId='j57dy3049btafda9m2f5d2ggk987ph3f'.",
	],
	[
		"list_bus",
		"List business units filtered by orchestrator or status, newest first with cursor paging support. WHEN: use to get a portfolio overview or find BUs managed by a specific orchestrator. EXAMPLE: list_bus orchestratorId='alpha' status='live' limit=20.",
	],
	[
		"delete_bu",
		"Permanently delete a business unit by Convex document ID — this action is irreversible. WHEN: use only for test BUs or entities created in error; prefer status='archived' for real BUs. EXAMPLE: delete_bu buId='j57aaaaa...'.",
	],
	[
		"add_repo_mapping",
		"Register or update a GitHub repo to orchestrator mapping for webhook event routing. WHEN: use when adding a new repo to monitoring or changing which orchestrator handles its events. EXAMPLE: register_repo_mapping repo='vantageos-agency/vantage-peers' orchestrator='alpha' project='vantage-peers'.",
	],
	[
		"list_repo_mappings",
		"List all GitHub repo to orchestrator webhook mappings, newest first with cursor paging support. WHEN: use to audit which repos are monitored and verify routing before adding new mappings. EXAMPLE: list_repo_mappings limit=20 fields='lite'.",
	],
	[
		"remove_repo_mapping",
		"Delete a GitHub repo mapping by repo name, stopping webhook event routing for that repo. WHEN: use when a repo is archived or its events should no longer generate VP notifications. EXAMPLE: delete_repo_mapping repo='vantageos-agency/vantage-peers'.",
	],
	[
		"list_issues",
		"List tracked GitHub issues filtered by project, status, or assigned orchestrator, newest first. WHEN: use to triage open issues, find in-progress fixes, or review a project's bug backlog. EXAMPLE: list_issues project='vantage-peers' status='open' limit=20.",
	],
	[
		"get_issue",
		"Fetch a single GitHub issue by repo name and issue number, returning full tracking details. WHEN: use when routing a specific GitHub webhook event or verifying fix status on a known issue. EXAMPLE: get_issue repo='vantageos-agency/vantage-peers' issueNumber=667.",
	],
	[
		"update_issue_status",
		"Update the tracked status of a GitHub issue (open/in_progress/fixed/verified/closed). WHEN: use when work begins, a fix is committed, or QA confirms resolution. EXAMPLE: update_issue_status repo='vantageos-agency/vantage-peers' issueNumber=667 status='fixed'.",
	],
	[
		"link_commit_to_issue",
		"Link a fix commit SHA to a GitHub issue, recording the fixer and time of resolution. WHEN: use immediately after pushing a fix commit so the issue has an auditable commit reference. EXAMPLE: link_commit_to_issue repo='vantageos-agency/vantage-peers' issueNumber=667 commitSha='abc1234' fixedBy='alpha'.",
	],
	[
		"verify_issue",
		"Mark a GitHub issue as verified, confirming the fix was tested and the issue is resolved. WHEN: use after QA or the reporter confirms the fix works in the target environment. EXAMPLE: verify_issue repo='vantageos-agency/vantage-peers' issueNumber=667 verifiedBy='gamma'.",
	],
	[
		"issue_stats",
		"Get issue count statistics grouped by status, optionally scoped to a single project. WHEN: use for daily health checks or project retrospectives to measure issue throughput. EXAMPLE: issue_stats project='vantage-peers'.",
	],
	[
		"create_fix_pattern",
		"Create a fix pattern in the knowledge base documenting symptom, root cause, and optional validated fix. WHEN: use after resolving a non-trivial bug so future agents can find and reuse the solution. EXAMPLE: create_fix_pattern symptom='hydration mismatch' rootCause='SSR/CSR time skew' tags=['next.js'] stack=['next.js','convex'] sourceProject='vantage-starter' createdBy='alpha' severity='major'.",
	],
	[
		"add_fix_attempt",
		"Add a fix attempt record to a pattern with description, outcome, and optional commit reference. WHEN: use after each fix attempt (successful or not) to build a complete fix history. EXAMPLE: create_fix_attempt patternId='j57aaaaa...' description='Added suppressHydrationWarning' worked=true why='Prevents mismatches on date fields' createdBy='beta'.",
	],
	[
		"validate_fix",
		"Set or update the validated fix description on a fix pattern after confirming it works. WHEN: use after a fix attempt succeeds to promote it as the canonical solution on the pattern. EXAMPLE: check_fix patternId='j57aaaaa...' validatedFix='Add suppressHydrationWarning to date elements'.",
	],
	[
		"search_fix_patterns",
		"Semantic search over fix patterns by symptom description, ranked by relevance. WHEN: call BEFORE fixing any bug to check if a matching pattern exists and reuse the validated fix. EXAMPLE: search_fix_patterns query='message disappears after sending on mobile' limit=5.",
	],
	[
		"list_fix_patterns",
		"List fix patterns filtered by source project, newest first with cursor paging support. WHEN: use to audit the knowledge base or review all patterns for a specific project. EXAMPLE: list_fix_patterns project='vantage-starter' limit=20.",
	],
	[
		"link_issue_to_pattern",
		"Link a VantagePeers issue to a fix pattern creating a bidirectional reference. WHEN: use after creating a fix pattern for an issue to connect the symptom record with the bug tracker. EXAMPLE: link_issue_to_pattern patternId='j57aaaaa...' issueId='j57bbbbb...'.",
	],
	[
		"get_mission_template",
		"Fetch a mission template by name with all steps, or null if not found. WHEN: use before instantiate_template_into_mission to inspect steps and verify the template exists. EXAMPLE: get_mission_template name='issue-resolution-v2'.",
	],
	[
		"update_mission_template",
		"Create or upsert a mission template by name; existing templates are overwritten. WHEN: use to define or refine reusable multi-step workflow blueprints for recurring mission types. EXAMPLE: update_mission_template name='issue-resolution-v2' steps=[{title:'Triage',description:'...'}] createdBy='alpha'.",
	],
	[
		"instantiate_template_into_mission",
		"Create one task per template step inside a mission, pre-assigned to each step's declared orchestrator. WHEN: use after create_mission to fan out a standard workflow from a template in one call. EXAMPLE: instantiate_template_into_mission templateName='issue-resolution-v2' missionId='k57a36y8...' callerOrchestrator='alpha'.",
	],
	[
		"add_deployment",
		"Register a Convex deployment for proactive error monitoring via 5-minute cron polling. WHEN: use when setting up a new deployment that should auto-create GitHub issues on detected errors. EXAMPLE: register_deployment name='vantage-prod' deploymentUrl='https://vantage-prod.convex.cloud' deployKeyEnvVar='DEPLOY_KEY_PROD' githubRepo='vantageos-agency/vantage-peers' orchestrator='alpha'.",
	],
	[
		"remove_deployment",
		"Deactivate a monitored deployment, stopping cron polling while preserving the historical record. WHEN: use when a deployment is retired or moved to a different monitoring config. EXAMPLE: delete_deployment name='vantage-prod'.",
	],
	[
		"list_errors",
		"List detected errors from monitored deployments with dedup counts and linked GitHub issue numbers. WHEN: use to triage production errors, identify recurring failures, or find the latest crash report. EXAMPLE: list_errors deployment='vantage-prod' limit=20 fields='full'.",
	],
	[
		"get_error",
		"Fetch a single error log entry by Convex document ID, including full stack trace and issue linkage. WHEN: use after list_errors to retrieve the full stack trace for a specific error entry. EXAMPLE: get_error errorId='j57dy3049btafda9m2f5d2ggk987ph3f'.",
	],
	[
		"whoami",
		"Returns the orchestrator identity baked into the current bearer's scope context. WHEN: call this on skill startup to avoid asking the user for their orchestrator_id. EXAMPLE: a fresh Claude.ai connector calls whoami first, then uses suggested_orchestrator_id as `from` on all subsequent send_message / create_task calls.",
	],
	[
		"validate_task_payload",
		"Dry-run lint for VP write-path tools — checks all validation axes and returns failures with fix snippets. " +
			"WHEN: call before create_task / update_task / complete_task / send_message to catch all violations in one pass. " +
			"EXAMPLE: validate_task_payload tool_name='complete_task' payload={taskId:'k...',completionNote:'PR #667 merged SHA abc1234'}.",
	],
	// Canonical aliases (B2 §1 standard names)
	[
		"register_repo_mapping",
		"Register or update a GitHub repo to orchestrator mapping for webhook event routing. WHEN: use when adding a new repo to monitoring or changing which orchestrator handles its events. EXAMPLE: register_repo_mapping repo='vantageos-agency/vantage-peers' orchestrator='alpha' project='vantage-peers'.",
	],
	[
		"delete_repo_mapping",
		"Delete a GitHub repo mapping by repo name, stopping webhook event routing for that repo. WHEN: use when a repo is archived or its events should no longer generate VP notifications. EXAMPLE: delete_repo_mapping repo='vantageos-agency/vantage-peers'.",
	],
	[
		"register_deployment",
		"Register a Convex deployment for proactive error monitoring via 5-minute cron polling. WHEN: use when setting up a new deployment that should auto-create GitHub issues on detected errors. EXAMPLE: register_deployment name='vantage-prod' deploymentUrl='https://vantage-prod.convex.cloud' deployKeyEnvVar='DEPLOY_KEY_PROD' githubRepo='vantageos-agency/vantage-peers' orchestrator='alpha'.",
	],
	[
		"delete_deployment",
		"Deactivate a monitored deployment, stopping cron polling while preserving the historical record. WHEN: use when a deployment is retired or moved to a different monitoring config. EXAMPLE: delete_deployment name='vantage-prod'.",
	],
	[
		"check_mandate_spending",
		"Check whether a proposed token spend is within a mandate's AP2 spending limits. WHEN: call before each service transaction to prevent over-spend and get within/exceeded status. EXAMPLE: check_mandate_spending mandateId='j57aaaaa...' proposedAmount=500.",
	],
	[
		"check_fix",
		"Set or update the validated fix description on a fix pattern after confirming it works. WHEN: use after a fix attempt succeeds to promote it as the canonical solution on the pattern. EXAMPLE: check_fix patternId='j57aaaaa...' validatedFix='Add suppressHydrationWarning to date elements'.",
	],
	[
		"create_fix_attempt",
		"Add a fix attempt record to a pattern with description, outcome, and optional commit reference. WHEN: use after each fix attempt (successful or not) to build a complete fix history. EXAMPLE: create_fix_attempt patternId='j57aaaaa...' description='Added suppressHydrationWarning' worked=true why='Prevents mismatches on date fields' createdBy='beta'.",
	],
	[
		"create_task_dependency",
		"Add dependency task IDs to a task so it cannot start until all listed tasks complete. WHEN: use when creating a task that depends on prior work not yet captured in dependsOn. EXAMPLE: create_task_dependency taskId='k178d3ns...' dependsOn=['k17bbbbb...'] callerOrchestrator='alpha'.",
	],
	[
		"update_summary",
		"Update the current-work summary for an orchestrator instance, visible via list_peers. WHEN: call at the start of each session and after major context switches to keep peers informed. EXAMPLE: update_summary orchestratorId='alpha' instanceId='alpha-vps' summary='Standardizing 86 tool descriptions for B2 PR#667'.",
	],
	[
		"create_diary",
		"Write or upsert a diary entry for a specific date and orchestrator with highlights and blockers. WHEN: call at end of session to record what was accomplished, learned, and what blocked progress. EXAMPLE: create_diary date='2026-06-06' orchestrator='gamma' content='Standardized 86 descriptions...'.",
	],
];

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("B2 §4 tool description schema compliance", () => {
	for (const [name, desc] of TOOL_REGISTRY) {
		it(`${name} — name is compliant or legacy alias`, () => {
			const isCompliant = ALLOWED_VERB_REGEX.test(name);
			const isLegacy = LEGACY_ALIASES.has(name);
			expect(
				isCompliant || isLegacy,
				`Tool "${name}" is neither on the allowed-verb whitelist nor on the legacy alias list. ` +
					`Allowed verbs: create|get|list|update|delete|search|send|check|store|recall|whoami|mark|register|link|complete|start|accept|settle|patch|revoke|hybrid_search|text_search|soft_delete|issue_stats|validate_task_payload`,
			).toBe(true);
		});

		it(`${name} — description length 80-500 chars`, () => {
			expect(
				desc.length,
				`"${name}" description is ${desc.length} chars (must be 80-500).`,
			).toBeGreaterThanOrEqual(80);
			expect(
				desc.length,
				`"${name}" description is ${desc.length} chars (must be 80-500).`,
			).toBeLessThanOrEqual(500);
		});

		it(`${name} — description contains WHEN clause`, () => {
			expect(
				desc,
				`"${name}" description missing WHEN clause (B2 §4 requires WHEN: ...)`,
			).toContain("WHEN:");
		});

		it(`${name} — description contains EXAMPLE`, () => {
			expect(
				desc,
				`"${name}" description missing EXAMPLE (B2 §3+§4 require EXAMPLE: ...)`,
			).toContain("EXAMPLE:");
		});
	}
});

describe("B2 §1 canonical verb migration coverage", () => {
	const canonicalTools = TOOL_REGISTRY.map(([name]) => name).filter(
		(name) => !LEGACY_ALIASES.has(name),
	);

	const expectedCanonicals = [
		"register_repo_mapping",
		"delete_repo_mapping",
		"register_deployment",
		"delete_deployment",
		"check_mandate_spending",
		"check_fix",
		"create_fix_attempt",
		"create_task_dependency",
		"update_summary",
		"create_diary",
	];

	for (const canonical of expectedCanonicals) {
		it(`canonical tool "${canonical}" is registered`, () => {
			expect(canonicalTools).toContain(canonical);
		});
	}

	it("all legacy aliases are covered by a canonical counterpart", () => {
		const legacyToCanonical: Record<string, string> = {
			add_repo_mapping: "register_repo_mapping",
			remove_repo_mapping: "delete_repo_mapping",
			add_deployment: "register_deployment",
			remove_deployment: "delete_deployment",
			validate_mandate_spending: "check_mandate_spending",
			validate_fix: "check_fix",
			add_fix_attempt: "create_fix_attempt",
			add_task_dependency: "create_task_dependency",
			set_summary: "update_summary",
			write_diary: "create_diary",
		};
		for (const [legacy, canonical] of Object.entries(legacyToCanonical)) {
			expect(
				canonicalTools,
				`Canonical tool "${canonical}" for legacy "${legacy}" is not in registry`,
			).toContain(canonical);
		}
	});
});

describe("B2 §4 aggregate coverage", () => {
	it("total registered tools >= 97 (87 original + 10 canonical aliases)", () => {
		expect(TOOL_REGISTRY.length).toBeGreaterThanOrEqual(97);
	});

	it("all descriptions contain WHEN:", () => {
		const missing = TOOL_REGISTRY.filter(([, desc]) => !desc.includes("WHEN:")).map(([name]) => name);
		expect(missing, `Tools missing WHEN: ${missing.join(", ")}`).toHaveLength(0);
	});

	it("all descriptions contain EXAMPLE:", () => {
		const missing = TOOL_REGISTRY.filter(([, desc]) => !desc.includes("EXAMPLE:")).map(([name]) => name);
		expect(missing, `Tools missing EXAMPLE: ${missing.join(", ")}`).toHaveLength(0);
	});

	it("all descriptions are within 80-500 char bounds", () => {
		const violations = TOOL_REGISTRY.filter(
			([, desc]) => desc.length < 80 || desc.length > 500,
		).map(([name, desc]) => `${name}(${desc.length})`);
		expect(violations, `Out-of-bounds: ${violations.join(", ")}`).toHaveLength(0);
	});
});
