// ─────────────────────────────────────────────────────────────────────────────
// bulk_complete_tasks.tool.test.ts — PR-F TDD-RED phase
// ─────────────────────────────────────────────────────────────────────────────
//
// Pins the MCP tool registration + Zod args schema contract for
// `bulk_complete_tasks`.
//
// Mission: k571gcctka8mq5jbkgpj0a0b2n892ctg (VP-MCP top level Bloc A)
// Branch: feat/vpmcp-f-bulk-complete-tasks
//
// T-GREEN must export from mcp-server/src/tools.ts:
//   - BULK_COMPLETE_TASKS_TOOL_NAME: string — exactly "bulk_complete_tasks"
//   - bulkCompleteTasksArgsSchema: z.ZodObject — must enforce:
//       filter: required object { autoGeneratedOnly?: boolean; assignedTo?: string }
//       dryRun: optional boolean, default true
//       completionNoteTemplate: optional string
//       callerOrchestrator: optional string
//
// Both imports will throw "does not provide an export named …" until T-GREEN
// ships them — that is the RED contract.
// ─────────────────────────────────────────────────────────────────────────────

import { describe, expect, it } from "vitest";

// Expected exports from T-GREEN — these do NOT exist in tools.ts yet → RED
// @ts-expect-error — RED: exports do not exist yet, will exist post-T-GREEN
import { BULK_COMPLETE_TASKS_TOOL_NAME, bulkCompleteTasksArgsSchema } from "../tools.js";

describe("bulk_complete_tasks MCP tool registration + args schema (PR-F RED)", () => {

	// ── Tool registration ────────────────────────────────────────────────────
	it("tool name is 'bulk_complete_tasks' and is registered in the MCP tool list", () => {
		// Will fail until BULK_COMPLETE_TASKS_TOOL_NAME is exported from tools.ts
		expect(typeof BULK_COMPLETE_TASKS_TOOL_NAME).toBe("string");
		expect(BULK_COMPLETE_TASKS_TOOL_NAME).toBe("bulk_complete_tasks");
	});

	// ── Zod args schema ──────────────────────────────────────────────────────
	it("args schema: filter required, dryRun defaults true, completionNoteTemplate optional", () => {
		// Will fail until bulkCompleteTasksArgsSchema is exported from tools.ts

		// Valid — minimal: filter required, dryRun defaults to true
		const minimal = bulkCompleteTasksArgsSchema.parse({
			filter: { autoGeneratedOnly: true },
		});
		expect(minimal.filter).toMatchObject({ autoGeneratedOnly: true });
		// dryRun must default to true when omitted (safety default)
		expect(minimal.dryRun).toBe(true);

		// Valid — explicit dryRun=false
		const withDryRunFalse = bulkCompleteTasksArgsSchema.parse({
			filter: { autoGeneratedOnly: true },
			dryRun: false,
		});
		expect(withDryRunFalse.dryRun).toBe(false);

		// Valid — completionNoteTemplate present
		const withTemplate = bulkCompleteTasksArgsSchema.parse({
			filter: { autoGeneratedOnly: true },
			completionNoteTemplate: "bulk-cleanup: cron-spam day {{day}}",
		});
		expect(withTemplate.completionNoteTemplate).toBe("bulk-cleanup: cron-spam day {{day}}");

		// Valid — callerOrchestrator present
		const withCaller = bulkCompleteTasksArgsSchema.parse({
			filter: { autoGeneratedOnly: true },
			callerOrchestrator: "sigma",
		});
		expect(withCaller.callerOrchestrator).toBe("sigma");

		// Invalid — filter missing → must throw
		expect(() =>
			bulkCompleteTasksArgsSchema.parse({ dryRun: false }),
		).toThrow();

		// Invalid — filter is not an object
		expect(() =>
			bulkCompleteTasksArgsSchema.parse({ filter: "autoGeneratedOnly" }),
		).toThrow();

		// Invalid — dryRun is not a boolean
		expect(() =>
			bulkCompleteTasksArgsSchema.parse({ filter: {}, dryRun: "yes" }),
		).toThrow();

		// Valid — empty filter object (no filter criteria = all open tasks; caller's choice)
		const emptyFilter = bulkCompleteTasksArgsSchema.parse({ filter: {} });
		expect(emptyFilter.filter).toBeDefined();
	});
});
