// ─────────────────────────────────────────────────────────────────────────────
// list_tasks.tool.test.ts — PR-E TDD-RED phase
// ─────────────────────────────────────────────────────────────────────────────
//
// Pins the MCP tool description + args schema contract for `list_tasks`
// regarding the new `excludeAutoGenerated` filter.
//
// Mission: k571gcctka8mq5jbkgpj0a0b2n892ctg (VP-MCP top level Bloc A)
// Task ref: k173zpgb9hgdp5jewtg5j9t549892gx1
//
// T-GREEN must export from mcp-server/src/tools.ts:
//   - LIST_TASKS_TOOL_DESCRIPTION: string — must contain "excludeAutoGenerated"
//     and a usage hint explaining that it hides cron-spawned tasks
//   - listTasksArgsSchema: z.ZodObject — must accept { excludeAutoGenerated:
//     z.boolean().optional() } alongside existing args, and must parse
//     correctly when excludeAutoGenerated is true/false/undefined.
//
// Both imports will throw "does not provide an export named …" until T-GREEN
// ships them — that is the RED contract.
// ─────────────────────────────────────────────────────────────────────────────

import { describe, expect, it } from "vitest";

// Expected exports from T-GREEN — these do NOT exist in tools.ts yet → RED
// @ts-expect-error — RED: exports do not exist yet, will exist post-T-GREEN
import { LIST_TASKS_TOOL_DESCRIPTION, listTasksArgsSchema } from "../tools.js";

describe("list_tasks tool description + args schema — excludeAutoGenerated (PR-E RED)", () => {
	it("description mentions 'excludeAutoGenerated' with a usage hint about cron tasks", () => {
		// Will fail until LIST_TASKS_TOOL_DESCRIPTION is exported from tools.ts
		expect(typeof LIST_TASKS_TOOL_DESCRIPTION).toBe("string");
		expect(LIST_TASKS_TOOL_DESCRIPTION).toContain("excludeAutoGenerated");
		// Must explain the intent: filtering auto-generated / cron-spawned tasks
		expect(LIST_TASKS_TOOL_DESCRIPTION).toMatch(/cron|auto.?gen/i);
	});

	it("args schema accepts excludeAutoGenerated as an optional boolean", () => {
		// Will fail until listTasksArgsSchema is exported from tools.ts

		// Valid — excludeAutoGenerated absent (undefined)
		expect(listTasksArgsSchema.parse({})).toBeTruthy();

		// Valid — excludeAutoGenerated=true
		expect(
			listTasksArgsSchema.parse({ excludeAutoGenerated: true }),
		).toMatchObject({ excludeAutoGenerated: true });

		// Valid — excludeAutoGenerated=false
		expect(
			listTasksArgsSchema.parse({ excludeAutoGenerated: false }),
		).toMatchObject({ excludeAutoGenerated: false });

		// Invalid — non-boolean value rejected
		expect(() =>
			listTasksArgsSchema.parse({ excludeAutoGenerated: "yes" }),
		).toThrow();

		// Invalid — numeric value rejected
		expect(() =>
			listTasksArgsSchema.parse({ excludeAutoGenerated: 1 }),
		).toThrow();

		// Coexists with existing args
		expect(
			listTasksArgsSchema.parse({
				assignedTo: "pi",
				status: "todo",
				limit: 20,
				fields: "lite",
				excludeAutoGenerated: true,
			}),
		).toMatchObject({
			assignedTo: "pi",
			excludeAutoGenerated: true,
		});
	});
});
