/// <reference types="vite/client" />
/**
 * R-31 (backend-doctor, standard §15:420) — bulkComplete continues by
 * `ctx.scheduler.runAfter(0, internal…)`, not only by a caller re-calling it.
 *
 * Poles (a pole run under master alone would exercise the bypass, so the
 * tenant and RBAC poles run as an ORDINARY org member):
 *   BOUNDED    the public call closes ONE batch (the cap), never the pile.
 *   COMPLETE   after the scheduled continuations run, every matching row is
 *              closed, with the SAME completionNote (same bulkRunId).
 *   SHAPE      the return value is byte-identical to the caller-driven era:
 *              {count, sampleIds, bulkRunId, executedAt, cappedAt, remaining}.
 *   DRY-RUN    a preview schedules nothing.
 *   TENANT     the continuation does not close another org's rows.
 *   RBAC       the continuation keeps the caller's creator/assignee check.
 *   TERMINATES a drain that is finished leaves nothing pending.
 *   FAILURE    a later batch that fails (RBAC, closure gate) is not silent: the
 *              scheduled run ends "failed" (operator log) AND the caller who
 *              follows the documented protocol (re-call the same filter until
 *              `remaining` is gone) receives the SAME refusal synchronously.
 */

import { convexTest } from "convex-test";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { api } from "../_generated/api";
import schema from "../schema";

const modules = Object.fromEntries(
	Object.entries(import.meta.glob("../**/*.ts")).filter(
		([path]) =>
			!path.includes("ragSync") &&
			!path.includes("search") &&
			!path.includes("backfill"),
	),
);

const createT = () => convexTest(schema, modules);
type T = ReturnType<typeof createT>;
type Identity = Parameters<T["withIdentity"]>[0];

const CAP = 500; // BULK_COMPLETE_HARD_CAP

const asMaster = (t: T) =>
	t.withIdentity({ subject: "test-service-account-user-id" } as Identity);
const asMember = (t: T, orgSlug: string) =>
	t.withIdentity({
		subject: `member-of-${orgSlug}`,
		organizationId: orgSlug,
		organizationSlug: orgSlug,
	} as Identity);

async function seedOrg(t: T, slug: string, roster: string[]) {
	await t.run(async (ctx) => {
		await ctx.db.insert("client_org_mapping", {
			clerkOrgSlug: slug,
			allowedOrchestrators: roster,
			scopes: ["view-own-tasks"],
			displayName: slug,
			isActive: true,
			createdAt: Date.now(),
		});
	});
}

async function seedClosureConfig(t: T) {
	await t.run(async (ctx) => {
		await ctx.db.insert("taskClosureConfig", {
			key: "billableProjects",
			value: [],
			updatedAt: Date.now(),
		});
	});
}

async function seedRows(
	t: T,
	n: number,
	o: { orgId?: string; assignedTo: string; createdBy: string; project?: string },
) {
	await t.run(async (ctx) => {
		for (let i = 0; i < n; i++) {
			const now = Date.now();
			await ctx.db.insert("tasks", {
				title: `row ${o.orgId ?? "none"} ${o.assignedTo} ${i}`,
				assignedTo: o.assignedTo,
				createdBy: o.createdBy,
				priority: "low",
				status: "todo",
				...(o.orgId === undefined ? {} : { orgId: o.orgId }),
				...(o.project === undefined ? {} : { project: o.project }),
				createdAt: now,
				updatedAt: now,
			});
		}
	});
}

const rows = (t: T) => t.run((ctx) => ctx.db.query("tasks").collect());
const scheduledFns = (t: T) =>
	t.run((ctx) => ctx.db.system.query("_scheduled_functions").collect());
const pendingFns = async (t: T) =>
	(await scheduledFns(t)).filter((f) => f.state.kind === "pending");

const logged = vi.spyOn(console, "error").mockImplementation(() => undefined);

describe("tasks.bulkComplete — self-scheduled continuation (R-31)", () => {
	beforeEach(() => {
		vi.useFakeTimers();
		logged.mockClear();
	});
	afterEach(() => {
		vi.useRealTimers();
	});

	test("BOUNDED + COMPLETE + SHAPE: one batch per call, the pile drains by itself, one note across batches", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 1200, { assignedTo: "pi-r31", createdBy: "cron-x" });

		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "pi-r31" },
			dryRun: false,
			callerOrchestrator: "system",
		});

		// SHAPE — unchanged.
		expect(Object.keys(res).sort()).toEqual(
			["bulkRunId", "cappedAt", "count", "executedAt", "remaining", "sampleIds"].sort(),
		);
		expect(res.count).toBe(CAP);
		expect(res.cappedAt).toBe(CAP);
		expect(res.remaining).toBe(true);
		expect(res.sampleIds).toHaveLength(10);

		// BOUNDED — the public transaction closed one batch only.
		expect((await rows(t)).filter((r) => r.status === "done")).toHaveLength(CAP);

		await t.finishAllScheduledFunctions(vi.runAllTimers);

		// COMPLETE — everything closed, every row carries the first call's runId.
		const after = await rows(t);
		expect(after.filter((r) => r.status === "done")).toHaveLength(1200);
		const notes = new Set(after.map((r) => r.completionNote));
		expect(notes.size).toBe(1);
		expect([...notes][0]).toContain(res.bulkRunId);

		// TERMINATES — nothing is left pending.
		expect(await pendingFns(t)).toHaveLength(0);
	});

	test("under the cap: no continuation is scheduled and no cappedAt/remaining is reported", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 42, { assignedTo: "pi-r31-small", createdBy: "cron-x" });
		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "pi-r31-small" },
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(res.count).toBe(42);
		expect(res.cappedAt).toBeUndefined();
		expect(res.remaining).toBeUndefined();
		expect(await scheduledFns(t)).toHaveLength(0);
	});

	test("DRY-RUN: a preview over the cap schedules nothing and closes nothing", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 700, { assignedTo: "pi-r31-dry", createdBy: "cron-x" });
		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "pi-r31-dry" },
		});
		expect(res.remaining).toBe(true);
		expect(await scheduledFns(t)).toHaveLength(0);
		await t.finishAllScheduledFunctions(vi.runAllTimers);
		expect((await rows(t)).filter((r) => r.status === "done")).toHaveLength(0);
	});

	test("TENANT: an ordinary member's continuation closes its own org's rows and never another's", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma"]);
		await seedOrg(t, "org-b", ["sigma"]);
		await seedRows(t, CAP + 40, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		await seedRows(t, 30, { orgId: "org-b", assignedTo: "sigma", createdBy: "sigma" });

		const res = await asMember(t, "org-a").mutation(api.tasks.bulkComplete, {
			filter: { assignedTo: "sigma" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		expect(res.remaining).toBe(true);
		await t.finishAllScheduledFunctions(vi.runAllTimers);

		const after = await rows(t);
		expect(after.filter((r) => r.orgId === "org-a" && r.status === "done")).toHaveLength(CAP + 40);
		expect(after.filter((r) => r.orgId === "org-b" && r.status === "done")).toHaveLength(0);
	});

	test("RBAC: the continuation keeps the creator/assignee check and does not run away", async () => {
		const t = createT();
		await seedClosureConfig(t);
		// roster admits both names; the caller is "sigma", NOT eta's creator/assignee.
		await seedOrg(t, "org-a", ["sigma", "eta"]);
		await seedRows(t, CAP + 10, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		await seedRows(t, 3, { orgId: "org-a", assignedTo: "eta", createdBy: "eta" });

		const res = await asMember(t, "org-a").mutation(api.tasks.bulkComplete, {
			filter: { status: "todo" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		expect(res.remaining).toBe(true);
		await t.finishAllScheduledFunctions(vi.runAllTimers).catch(() => undefined);

		const after = await rows(t);
		// eta's rows were never closed by a caller who is neither creator nor assignee.
		expect(after.filter((r) => r.assignedTo === "eta" && r.status === "done")).toHaveLength(0);
		expect(await pendingFns(t)).toHaveLength(0);
	});

	test("FAILURE (closure gate): a later batch that fails ends 'failed' in the scheduler AND the caller's re-call gets the same refusal", async () => {
		const t = createT();
		await t.run(async (ctx) => {
			await ctx.db.insert("taskClosureConfig", {
				key: "billableProjects",
				value: ["bill-p"],
				updatedAt: Date.now(),
			});
		});
		await seedRows(t, CAP, { assignedTo: "pi-r31-fail", createdBy: "cron-x" });
		// Created last, so it is NOT in the first batch: a billable task never started.
		await seedRows(t, 1, {
			assignedTo: "pi-r31-fail",
			createdBy: "cron-x",
			project: "bill-p",
		});
		const filter = { autoGeneratedOnly: true, assignedTo: "pi-r31-fail" } as const;

		const first = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter,
			dryRun: false,
			callerOrchestrator: "system",
		});
		// Exactly CAP matched + 1 overflow: the first call is clean and says so.
		expect(first.count).toBe(CAP);
		expect(first.remaining).toBe(true);

		await t.finishAllScheduledFunctions(vi.runAllTimers).catch(() => undefined);

		// Operator surface: the scheduled continuation is recorded as failed, and the
		// log names the run and the reason.
		const failed = (await scheduledFns(t)).filter((f) => f.state.kind === "failed");
		expect(failed).toHaveLength(1);
		expect(logged).toHaveBeenCalledWith(
			expect.stringContaining(`run ${first.bulkRunId} stopped`),
		);
		expect(logged).toHaveBeenCalledWith(
			expect.stringContaining("TASK_NEVER_STARTED_BILLABLE"),
		);
		// Nothing was closed past the refusal.
		const billable = (await rows(t)).filter((r) => r.project === "bill-p");
		expect(billable[0].status).toBe("todo");

		// Caller surface: the documented re-call hits the same refusal in the foreground.
		await expect(
			asMaster(t).mutation(api.tasks.bulkComplete, {
				filter,
				dryRun: false,
				callerOrchestrator: "system",
			}),
		).rejects.toThrow(/TASK_NEVER_STARTED_BILLABLE/);
	});

	test("FAILURE (RBAC): the failed continuation is recorded and the caller's re-call is refused in the foreground", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma", "eta"]);
		await seedRows(t, CAP + 10, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		await seedRows(t, 3, { orgId: "org-a", assignedTo: "eta", createdBy: "eta" });
		const member = asMember(t, "org-a");

		await member.mutation(api.tasks.bulkComplete, {
			filter: { status: "todo" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		await t.finishAllScheduledFunctions(vi.runAllTimers).catch(() => undefined);

		const failed = (await scheduledFns(t)).filter((f) => f.state.kind === "failed");
		expect(failed).toHaveLength(1);
		expect(logged).toHaveBeenCalledWith(expect.stringContaining("RBAC_DENIED"));

		await expect(
			member.mutation(api.tasks.bulkComplete, {
				filter: { status: "todo" },
				dryRun: false,
				callerOrchestrator: "sigma",
			}),
		).rejects.toThrow(/RBAC_DENIED/);
		// The preview is refused too, so the caller cannot mistake the stuck pile for "nothing left".
		await expect(
			member.mutation(api.tasks.bulkComplete, {
				filter: { status: "todo" },
				callerOrchestrator: "sigma",
			}),
		).rejects.toThrow(/RBAC_DENIED/);
	});
});
