/// <reference types="vite/client" />
/**
 * M4 ruling 3 prep: before the org-key-by-ID deploy, the operator prints how many
 * scheduled `tasks:bulkCompleteContinue` jobs are still PENDING and carry no org
 * ID in their forwarded scope. Such a job was scheduled by the pre-M4 code; once
 * M4 matches rows by ID only it would match none of its org's rows.
 *
 * `migrations/bulkCompleteContinuationAudit:countPendingWithoutOrgId` is a
 * read-only internalQuery. Three poles: PRESENT (jobs without an ID are counted
 * and named), ABSENT (none pending -> an empty SUCCESS with a zero count and the
 * scan stated), and a job that is NOT a bulk continuation, is already finished,
 * or carries an ID is never counted.
 */
import { convexTest } from "convex-test";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { internal } from "../_generated/api";
import schema from "../schema";

const modules = Object.fromEntries(
	Object.entries(import.meta.glob("../**/*.ts")).filter(
		([path]) =>
			!path.includes("ragSync") &&
			!path.includes("search") &&
			!path.includes("backfill"),
	),
);

const createT = () => convexTest(schema, modules);
type T = ReturnType<typeof createT>;

const FAR = 1000 * 60 * 60 * 24 * 365; // stays pending for the whole test

const continuationArgs = (
	over: { orgClerkId?: string; orgSlug?: string | null; isMaster?: boolean } = {},
) => ({
	filter: { autoGeneratedOnly: true },
	scope: {
		userId: "u",
		orgSlug: over.orgSlug === undefined ? "acme" : over.orgSlug,
		...(over.orgClerkId === undefined ? {} : { orgClerkId: over.orgClerkId }),
		allowedOrchestrators: ["a"],
		isMaster: over.isMaster ?? false,
	},
	callerOrchestrator: "a",
	isFleetSystem: false,
	note: "n",
	bulkRunId: "run",
});

async function schedule(t: T, args: ReturnType<typeof continuationArgs>) {
	return await t.run((ctx) =>
		ctx.scheduler.runAfter(FAR, internal.tasks.bulkCompleteContinue, args),
	);
}

beforeEach(() => {
	vi.useFakeTimers();
});
afterEach(() => {
	vi.useRealTimers();
});

describe("countPendingWithoutOrgId", () => {
	test("PRESENT: counts and names pending continuations whose scope has no org ID", async () => {
		const t = createT();
		const a = await schedule(t, continuationArgs());
		const b = await schedule(t, continuationArgs({ orgSlug: null, isMaster: true }));
		await schedule(t, continuationArgs({ orgClerkId: "org_abc123" }));

		const r = await t.query(
			internal.migrations.bulkCompleteContinuationAudit.countPendingWithoutOrgId,
			{},
		);
		expect(r.count).toBe(2);
		expect([...r.ids].sort()).toEqual([a, b].sort());
		expect(r.nonMasterCount).toBe(1);
		expect(r.pendingContinuations).toBe(3);
		expect(r.truncated).toBe(false);
	});

	test("ABSENT: nothing pending is an empty success that says it scanned", async () => {
		const t = createT();
		const r = await t.query(
			internal.migrations.bulkCompleteContinuationAudit.countPendingWithoutOrgId,
			{},
		);
		expect(r).toMatchObject({
			count: 0,
			ids: [],
			nonMasterCount: 0,
			pendingContinuations: 0,
			truncated: false,
		});
		expect(r.scanned).toBe(0);
	});

	test("a cancelled job is never counted, and a continuation that carries an ID is not either", async () => {
		const t = createT();
		const done = await schedule(t, continuationArgs());
		await t.run((ctx) =>
			ctx.scheduler.runAfter(FAR, internal.tasks.bulkCompleteContinue, {
				...continuationArgs(),
				bulkRunId: "other",
			}),
		);
		await t.run(async (ctx) => {
			await ctx.scheduler.cancel(done);
		});
		const r = await t.query(
			internal.migrations.bulkCompleteContinuationAudit.countPendingWithoutOrgId,
			{},
		);
		expect(r.count).toBe(1);
		expect(r.ids).not.toContain(done);
	});

	test("a job set that exceeds the scan window reports truncated instead of a short count", async () => {
		const t = createT();
		for (let i = 0; i < 3; i++) await schedule(t, continuationArgs());
		const r = await t.query(
			internal.migrations.bulkCompleteContinuationAudit.countPendingWithoutOrgId,
			{ scanLimit: 2 },
		);
		expect(r.truncated).toBe(true);
		expect(r.scanned).toBe(2);
	});
});
