/// <reference types="vite/client" />
//
// bulkCompleteScale.test.ts — Day 163 RED-first (Pi, k171rbm2txe42jxzddyqakbg7n8ch7zr)
// ─────────────────────────────────────────────────────────────────────────────
//
// DEFECT 1: `bulkComplete`'s live path REFUSED once matched > 500
// (BULK_COMPLETE_HARD_CAP), instructing the caller to "narrow your filter"
// even when both filter fields were already at their narrowest
// (autoGeneratedOnly + assignedTo both set) — an un-followable instruction.
// The scan also stopped at cap+1, so the reported count was a scan-stop
// sentinel, not a total: a caller could not tell 501 from 500000.
//
// Both poles required:
//   1. RED — seeding > cap matching rows with every filter field already
//      narrowest must give the caller a TERMINATING route (batch-drain or
//      status-narrow), not an un-followable "narrow your filter" throw.
//   2. RED — the count must be labelled when truncated, exact when exact.
// ─────────────────────────────────────────────────────────────────────────────

import { convexTest } from "convex-test";
import { describe, expect, test } from "vitest";
import { api } from "../_generated/api";
import schema from "../schema";

const modules = Object.fromEntries(
	Object.entries(import.meta.glob("../**/*.ts")).filter(
		([path]) =>
			!path.includes("ragSync") &&
			!path.includes("search") &&
			!path.includes("backfill"),
	),
);

const createT = () => convexTest(schema, modules);

async function seedCronSpam(
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	t: ReturnType<typeof createT>,
	count: number,
	opts: { assignedTo: string },
): Promise<void> {
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	await t.run(async (ctx: any) => {
		for (let i = 0; i < count; i++) {
			const now = Date.now() + i;
			await ctx.db.insert("tasks", {
				title: `/check-messages run ${i}`,
				assignedTo: opts.assignedTo,
				priority: "medium",
				status: "todo",
				createdBy: "cron-checker",
				createdAt: now,
				updatedAt: now,
			});
		}
	});
}

describe("tasks.bulkComplete — scale past the hard cap (Day 163)", () => {
	test("RED: narrowest-possible filter (autoGeneratedOnly + assignedTo) at 800 rows has a terminating route, not an un-followable refusal", async () => {
		const t = createT();
		const assignedTo = "pi-bulk-narrowest";
		await seedCronSpam(t, 800, { assignedTo });

		// Old behavior: this threw BULK_HARD_CAP_EXCEEDED telling the caller
		// to "narrow your filter" — but autoGeneratedOnly + assignedTo were
		// ALREADY the narrowest available combination. New behavior: the call
		// must NOT throw; it drains a cap-sized batch and reports truncation.
		const first = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo },
			dryRun: false,
			callerOrchestrator: "system",
		});

		expect(first.count).toBe(500);
		expect(first.cappedAt).toBe(500);
		expect(first.remaining).toBe(true);

		// The caller has a TERMINATING route: repeat the identical call.
		// Because the first batch is now status="done", it drops out of the
		// non-done scan on the next call — the pile actually drains.
		const second = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo },
			dryRun: false,
			callerOrchestrator: "system",
		});

		expect(second.count).toBe(300);
		// Exact — the second call did not hit the cap.
		expect(second.cappedAt).toBeUndefined();
		expect(second.remaining).toBeUndefined();

		// A third call finds nothing left — exhausted, not another refusal.
		const third = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo },
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(third.count).toBe(0);
	});

	test("RED: status filter narrows the scan and is a valid standalone reductive predicate", async () => {
		const t = createT();
		const assignedTo = "pi-bulk-status";
		// Seed 10 cron-spam rows in "todo" and 10 in "in_progress" — status
		// filter must scan ONLY the requested status.
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		await t.run(async (ctx: any) => {
			for (let i = 0; i < 10; i++) {
				const now = Date.now() + i;
				await ctx.db.insert("tasks", {
					title: `/check-messages todo ${i}`,
					assignedTo,
					priority: "medium",
					status: "todo",
					createdBy: "cron-checker",
					createdAt: now,
					updatedAt: now,
				});
				await ctx.db.insert("tasks", {
					title: `/check-messages ip ${i}`,
					assignedTo,
					priority: "medium",
					status: "in_progress",
					createdBy: "cron-checker",
					createdAt: now,
					updatedAt: now,
				});
			}
		});

		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { status: "todo" },
			dryRun: false,
			callerOrchestrator: "system",
		});

		// Only the 10 "todo" rows closed — status alone is a valid, working
		// reductive predicate (previously the filter validator did not even
		// accept `status`).
		expect(result.count).toBe(10);

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		const stillInProgress: any[] = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			assignedTo,
			status: "in_progress",
			limit: 50,
			fields: "lite",
		});
		expect(stillInProgress.length).toBe(10);
	});

	test("RED: count is exact (no cappedAt/remaining) when the match count is under the cap", async () => {
		const t = createT();
		const assignedTo = "pi-bulk-exact";
		await seedCronSpam(t, 42, { assignedTo });

		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo },
			dryRun: false,
			callerOrchestrator: "system",
		});

		expect(result.count).toBe(42);
		expect(result.cappedAt).toBeUndefined();
		expect(result.remaining).toBeUndefined();
	});

	test("RED: dryRun preview at scale is also labelled truncated, never a bare scan-stop sentinel presented as a total", async () => {
		const t = createT();
		const assignedTo = "pi-bulk-dryrun-scale";
		await seedCronSpam(t, 900, { assignedTo });

		const preview = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo },
			dryRun: true,
		});

		expect(preview.count).toBe(500);
		expect(preview.cappedAt).toBe(500);
		expect(preview.remaining).toBe(true);
		// dryRun must not mutate anything — no completedAt written.
		expect(preview.executedAt).toBeUndefined();
	});

	test("RED: empty filter is still refused regardless of the status addition (BULK_FILTER_TOO_BROAD)", async () => {
		const t = createT();
		await expect(
			t.mutation(api.tasks.bulkComplete, {
				filter: {},
				dryRun: true,
			}),
		).rejects.toThrow(/BULK_FILTER_TOO_BROAD/);
	});
});
