/// <reference types="vite/client" />
/**
 * R-31 (backend-doctor, standard §15:420) — bulkComplete continues by
 * `ctx.scheduler.runAfter(0, internal…)`, not only by a caller re-calling it.
 *
 * Poles (a pole run under master alone would exercise the bypass, so the
 * tenant and RBAC poles run as an ORDINARY org member):
 *   BOUNDED    the public call closes ONE batch (the cap), never the pile.
 *   COMPLETE   after the scheduled continuations run, every matching row is
 *              closed, with the SAME completionNote (same bulkRunId).
 *   SHAPE      the return value is byte-identical to the caller-driven era:
 *              {count, sampleIds, bulkRunId, executedAt, cappedAt, remaining}.
 *   DRY-RUN    a preview schedules nothing.
 *   TENANT     the continuation does not close another org's rows.
 *   RBAC       the continuation keeps the caller's creator/assignee check.
 *   TERMINATES a drain that is finished leaves nothing pending.
 *   RUN ROW    every live run has a status row keyed by the bulkRunId the first
 *              call returned (status, closed, remaining, failureReason), readable
 *              through tasks:getBulkCompleteRun by the run's own org (or master)
 *              and by nobody else.
 *   FAILURE    a later batch that fails (RBAC, closure gate) is not silent: the
 *              run row says "failed" with the reason, the rows stay open, and the
 *              caller who re-calls the same filter meets the same refusal.
 */

import { convexTest } from "../../tests/fixtures/convexTestWithServiceAccount";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { testClerkOrgId } from "../../tests/fixtures/testClerkOrgId";
import { api } from "../_generated/api";
import schema from "../schema";

const modules = Object.fromEntries(
	Object.entries(import.meta.glob("../**/*.ts")).filter(
		([path]) =>
			!path.includes("ragSync") &&
			!path.includes("search") &&
			!path.includes("backfill"),
	),
);

const createT = () => convexTest(schema, modules);
type T = ReturnType<typeof createT>;
type Identity = Parameters<T["withIdentity"]>[0];

const CAP = 500; // BULK_COMPLETE_HARD_CAP

const asMaster = (t: T) =>
	t.withIdentity({ subject: "test-service-account-user-id" } as Identity);
const asMember = (t: T, orgSlug: string) =>
	t.withIdentity({
		subject: `member-of-${orgSlug}`,
		organizationId: orgSlug,
		org_id: testClerkOrgId(orgSlug),
		organizationSlug: orgSlug,
	} as Identity);

async function seedOrg(t: T, slug: string, roster: string[]) {
	await t.run(async (ctx) => {
		await ctx.db.insert("client_org_mapping", {
			clerkOrgSlug: slug,
			clerkOrgId: testClerkOrgId(slug),
			allowedOrchestrators: roster,
			scopes: ["view-own-tasks"],
			displayName: slug,
			isActive: true,
			createdAt: Date.now(),
		});
	});
}

async function seedClosureConfig(t: T) {
	await t.run(async (ctx) => {
		await ctx.db.insert("taskClosureConfig", {
			key: "billableProjects",
			value: [],
			updatedAt: Date.now(),
		});
	});
}

async function seedRows(
	t: T,
	n: number,
	o: { orgId?: string; assignedTo: string; createdBy: string; project?: string },
) {
	await t.run(async (ctx) => {
		for (let i = 0; i < n; i++) {
			const now = Date.now();
			await ctx.db.insert("tasks", {
				title: `row ${o.orgId ?? "none"} ${o.assignedTo} ${i}`,
				assignedTo: o.assignedTo,
				createdBy: o.createdBy,
				priority: "low",
				status: "todo",
				...(o.orgId === undefined ? {} : { orgId: o.orgId, clerkOrgId: testClerkOrgId(o.orgId) }),
				...(o.project === undefined ? {} : { project: o.project }),
				createdAt: now,
				updatedAt: now,
			});
		}
	});
}

const rows = (t: T) => t.run((ctx) => ctx.db.query("tasks").collect());
const scheduledFns = (t: T) =>
	t.run((ctx) => ctx.db.system.query("_scheduled_functions").collect());
const pendingFns = async (t: T) =>
	(await scheduledFns(t)).filter((f) => f.state.kind === "pending");

const logged = vi.spyOn(console, "error").mockImplementation(() => undefined);

describe("tasks.bulkComplete — self-scheduled continuation (R-31)", () => {
	beforeEach(() => {
		vi.useFakeTimers();
		logged.mockClear();
	});
	afterEach(() => {
		vi.useRealTimers();
	});

	test("BOUNDED + COMPLETE + SHAPE: one batch per call, the pile drains by itself, one note across batches", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 1200, { assignedTo: "pi-r31", createdBy: "cron-x" });

		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "pi-r31" },
			dryRun: false,
			callerOrchestrator: "system",
		});

		// SHAPE — unchanged.
		expect(Object.keys(res).sort()).toEqual(
			["bulkRunId", "cappedAt", "count", "executedAt", "remaining", "sampleIds"].sort(),
		);
		expect(res.count).toBe(CAP);
		expect(res.cappedAt).toBe(CAP);
		expect(res.remaining).toBe(true);
		expect(res.sampleIds).toHaveLength(10);

		// BOUNDED — the public transaction closed one batch only.
		expect((await rows(t)).filter((r) => r.status === "done")).toHaveLength(CAP);

		await t.finishAllScheduledFunctions(vi.runAllTimers);

		// COMPLETE — everything closed, every row carries the first call's runId.
		const after = await rows(t);
		expect(after.filter((r) => r.status === "done")).toHaveLength(1200);
		const notes = new Set(after.map((r) => r.completionNote));
		expect(notes.size).toBe(1);
		expect([...notes][0]).toContain(res.bulkRunId);

		// TERMINATES — nothing is left pending.
		expect(await pendingFns(t)).toHaveLength(0);
	});

	test("under the cap: no continuation is scheduled and no cappedAt/remaining is reported", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 42, { assignedTo: "pi-r31-small", createdBy: "cron-x" });
		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "pi-r31-small" },
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(res.count).toBe(42);
		expect(res.cappedAt).toBeUndefined();
		expect(res.remaining).toBeUndefined();
		expect(await scheduledFns(t)).toHaveLength(0);
	});

	test("DRY-RUN: a preview over the cap schedules nothing and closes nothing", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 700, { assignedTo: "pi-r31-dry", createdBy: "cron-x" });
		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "pi-r31-dry" },
		});
		expect(res.remaining).toBe(true);
		expect(await scheduledFns(t)).toHaveLength(0);
		await t.finishAllScheduledFunctions(vi.runAllTimers);
		expect((await rows(t)).filter((r) => r.status === "done")).toHaveLength(0);
	});

	test("TENANT: an ordinary member's continuation closes its own org's rows and never another's", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma"]);
		await seedOrg(t, "org-b", ["sigma"]);
		await seedRows(t, CAP + 40, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		await seedRows(t, 30, { orgId: "org-b", assignedTo: "sigma", createdBy: "sigma" });

		const res = await asMember(t, "org-a").mutation(api.tasks.bulkComplete, {
			filter: { assignedTo: "sigma" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		expect(res.remaining).toBe(true);
		await t.finishAllScheduledFunctions(vi.runAllTimers);

		const after = await rows(t);
		expect(after.filter((r) => r.orgId === "org-a" && r.status === "done")).toHaveLength(CAP + 40);
		expect(after.filter((r) => r.orgId === "org-b" && r.status === "done")).toHaveLength(0);
	});

	test("RBAC: the continuation keeps the creator/assignee check and does not run away", async () => {
		const t = createT();
		await seedClosureConfig(t);
		// roster admits both names; the caller is "sigma", NOT eta's creator/assignee.
		await seedOrg(t, "org-a", ["sigma", "eta"]);
		await seedRows(t, CAP + 10, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		await seedRows(t, 3, { orgId: "org-a", assignedTo: "eta", createdBy: "eta" });

		const res = await asMember(t, "org-a").mutation(api.tasks.bulkComplete, {
			filter: { status: "todo" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		expect(res.remaining).toBe(true);
		await t.finishAllScheduledFunctions(vi.runAllTimers).catch(() => undefined);

		const after = await rows(t);
		// eta's rows were never closed by a caller who is neither creator nor assignee.
		expect(after.filter((r) => r.assignedTo === "eta" && r.status === "done")).toHaveLength(0);
		expect(await pendingFns(t)).toHaveLength(0);
	});

	const getRun = (t: T, who: "master" | "a" | "b" | "anon", bulkRunId: string) => {
		const c =
			who === "master"
				? asMaster(t)
				: who === "anon"
					? t
					: asMember(t, who === "a" ? "org-a" : "org-b");
		return c.query(api.tasks.getBulkCompleteRun, { bulkRunId });
	};

	test("RUN ROW: the first call's bulkRunId polls a row that goes running -> complete with the full count", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 1200, { assignedTo: "pi-r31-row", createdBy: "cron-x" });
		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "pi-r31-row" },
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(res.bulkRunId).toMatch(/^bulk-/);

		const mid = await getRun(t, "master", res.bulkRunId);
		expect(mid).toMatchObject({
			bulkRunId: res.bulkRunId,
			status: "running",
			closed: CAP,
			remaining: true,
			createdBy: "system",
		});
		expect(mid?.failureReason).toBeUndefined();

		await t.finishAllScheduledFunctions(vi.runAllTimers);
		const done = await getRun(t, "master", res.bulkRunId);
		expect(done).toMatchObject({ status: "complete", closed: 1200, remaining: false });
	});

	test("RUN ROW: a small run is 'complete' at once; a dry-run writes no row; an unknown id is null", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 4, { assignedTo: "pi-r31-small2", createdBy: "cron-x" });
		const filter = { autoGeneratedOnly: true, assignedTo: "pi-r31-small2" } as const;
		const preview = await asMaster(t).mutation(api.tasks.bulkComplete, { filter });
		expect(await getRun(t, "master", preview.bulkRunId)).toBeNull();
		const live = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter,
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(await getRun(t, "master", live.bulkRunId)).toMatchObject({
			status: "complete",
			closed: 4,
			remaining: false,
		});
		expect(await getRun(t, "master", "bulk-0-nope")).toBeNull();
	});

	test("RUN ROW ISOLATION: the run's own org reads it; another org gets nothing; anonymous is refused", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma"]);
		await seedOrg(t, "org-b", ["sigma"]);
		await seedRows(t, 3, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		const res = await asMember(t, "org-a").mutation(api.tasks.bulkComplete, {
			filter: { assignedTo: "sigma" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		expect(await getRun(t, "a", res.bulkRunId)).toMatchObject({ status: "complete", closed: 3, orgId: "org-a" });
		expect(await getRun(t, "b", res.bulkRunId)).toBeNull(); // another org: not served, id not an oracle
		expect(await getRun(t, "master", res.bulkRunId)).not.toBeNull();
		await expect(getRun(t, "anon", res.bulkRunId)).rejects.toThrow(/RBAC_DENIED/);
	});

	test("FAILURE (closure gate): a later batch that fails is recorded on the run row with its reason; nothing past the refusal closes; the re-call meets the same refusal", async () => {
		const t = createT();
		await t.run(async (ctx) => {
			await ctx.db.insert("taskClosureConfig", {
				key: "billableProjects",
				value: ["bill-p"],
				updatedAt: Date.now(),
			});
		});
		await seedRows(t, CAP, { assignedTo: "pi-r31-fail", createdBy: "cron-x" });
		// Created last, so it is NOT in the first batch: a billable task never started.
		await seedRows(t, 1, {
			assignedTo: "pi-r31-fail",
			createdBy: "cron-x",
			project: "bill-p",
		});
		const filter = { autoGeneratedOnly: true, assignedTo: "pi-r31-fail" } as const;

		const first = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter,
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(first.count).toBe(CAP);
		expect(first.remaining).toBe(true);

		await t.finishAllScheduledFunctions(vi.runAllTimers);

		// The surface a client reads: the run row.
		const run = await getRun(t, "master", first.bulkRunId);
		expect(run).toMatchObject({ status: "failed", closed: CAP, remaining: true });
		expect(run?.failureReason).toMatch(/TASK_NEVER_STARTED_BILLABLE/);
		// Operator log too.
		expect(logged).toHaveBeenCalledWith(
			expect.stringContaining(`run ${first.bulkRunId} stopped`),
		);
		// Nothing was closed past the refusal.
		expect((await rows(t)).filter((r) => r.project === "bill-p")[0].status).toBe("todo");
		expect(await pendingFns(t)).toHaveLength(0);

		// Caller surface: the documented re-call hits the same refusal in the foreground.
		await expect(
			asMaster(t).mutation(api.tasks.bulkComplete, {
				filter,
				dryRun: false,
				callerOrchestrator: "system",
			}),
		).rejects.toThrow(/TASK_NEVER_STARTED_BILLABLE/);
	});

	test("FAILURE (RBAC): the failed batch is on the run row, visible to the run's own org and not to another", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma", "eta"]);
		await seedOrg(t, "org-b", ["sigma"]);
		await seedRows(t, CAP + 10, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		await seedRows(t, 3, { orgId: "org-a", assignedTo: "eta", createdBy: "eta" });
		const member = asMember(t, "org-a");

		const first = await member.mutation(api.tasks.bulkComplete, {
			filter: { status: "todo" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		await t.finishAllScheduledFunctions(vi.runAllTimers);

		const run = await getRun(t, "a", first.bulkRunId);
		expect(run).toMatchObject({ status: "failed", closed: CAP, remaining: true });
		expect(run?.failureReason).toMatch(/RBAC_DENIED/);
		expect(await getRun(t, "b", first.bulkRunId)).toBeNull();

		await expect(
			member.mutation(api.tasks.bulkComplete, {
				filter: { status: "todo" },
				dryRun: false,
				callerOrchestrator: "sigma",
			}),
		).rejects.toThrow(/RBAC_DENIED/);
		await expect(
			member.mutation(api.tasks.bulkComplete, {
				filter: { status: "todo" },
				callerOrchestrator: "sigma",
			}),
		).rejects.toThrow(/RBAC_DENIED/);
	});

	// ── verifiedOrg: the run's org comes from the VERIFIED principal ────────────
	// On the MCP path the caller is the service account (master, no org). The
	// transport forwards the bearer's verified org as `verifiedOrg`; Convex believes
	// it from the service account only.

	test("VERIFIED ORG: a run made through the service account with verifiedOrg org-a is stamped org-a; org-b cannot read it even under the same creator name", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma"]);
		await seedOrg(t, "org-b", ["sigma"]);
		await seedRows(t, 3, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });

		const res = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { assignedTo: "sigma" },
			dryRun: false,
			callerOrchestrator: "sigma",
			verifiedOrg: { orgSlug: "org-a" },
		});

		expect(await getRun(t, "master", res.bulkRunId)).toMatchObject({
			orgId: "org-a",
			createdBy: "sigma",
			status: "complete",
		});
		// org-a's own member reads it; org-b (whose roster also holds "sigma") does not.
		expect(await getRun(t, "a", res.bulkRunId)).toMatchObject({ orgId: "org-a" });
		expect(await getRun(t, "b", res.bulkRunId)).toBeNull();
	});

	test("VERIFIED ORG: a member passing verifiedOrg is REFUSED (preview and live), and nothing is closed or written", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma"]);
		await seedOrg(t, "org-b", ["sigma"]);
		await seedRows(t, 3, { orgId: "org-b", assignedTo: "sigma", createdBy: "sigma" });
		const member = asMember(t, "org-b");

		for (const dryRun of [true, false]) {
			await expect(
				member.mutation(api.tasks.bulkComplete, {
					filter: { assignedTo: "sigma" },
					dryRun,
					callerOrchestrator: "sigma",
					verifiedOrg: { orgSlug: "org-a" },
				}),
			).rejects.toThrow(/RBAC_DENIED.*verified-org-not-trusted/);
		}
		expect((await rows(t)).filter((r) => r.status === "done")).toHaveLength(0);
		expect(await t.run((ctx) => ctx.db.query("bulk_complete_runs").collect())).toHaveLength(0);
	});

	test("VERIFIED ORG: the service account naming an unknown or inactive org is refused, not stamped", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedRows(t, 2, { assignedTo: "sigma", createdBy: "sigma" });
		await expect(
			asMaster(t).mutation(api.tasks.bulkComplete, {
				filter: { assignedTo: "sigma" },
				dryRun: false,
				callerOrchestrator: "system",
				verifiedOrg: { orgSlug: "no-such-org" },
			}),
		).rejects.toThrow(/org-not-active/);
		await t.run(async (ctx) => {
			await ctx.db.insert("client_org_mapping", {
				clerkOrgSlug: "off-org",
				clerkOrgId: testClerkOrgId("off-org"),
				allowedOrchestrators: ["sigma"],
				scopes: ["view-own-tasks"],
				displayName: "off",
				isActive: false,
				createdAt: Date.now(),
			});
		});
		await expect(
			asMaster(t).mutation(api.tasks.bulkComplete, {
				filter: { assignedTo: "sigma" },
				dryRun: false,
				callerOrchestrator: "system",
				verifiedOrg: { orgSlug: "off-org" },
			}),
		).rejects.toThrow(/org-not-active/);
		expect((await rows(t)).filter((r) => r.status === "done")).toHaveLength(0);
	});

	test("VERIFIED ORG: absent, the run is stamped with the caller's own org (member) or none (master), as before", async () => {
		const t = createT();
		await seedClosureConfig(t);
		await seedOrg(t, "org-a", ["sigma"]);
		await seedRows(t, 2, { orgId: "org-a", assignedTo: "sigma", createdBy: "sigma" });
		const mine = await asMember(t, "org-a").mutation(api.tasks.bulkComplete, {
			filter: { assignedTo: "sigma" },
			dryRun: false,
			callerOrchestrator: "sigma",
		});
		expect(await getRun(t, "master", mine.bulkRunId)).toMatchObject({ orgId: "org-a" });
		await seedRows(t, 1, { assignedTo: "zeta", createdBy: "cron-x" });
		const fleet = await asMaster(t).mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "zeta" },
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect((await getRun(t, "master", fleet.bulkRunId))?.orgId).toBeUndefined();
	});
});
