/// <reference types="vite/client" />
/**
 * THE TWO INHERITED TENANT STAMPS.
 *
 * Most write sites derive `orgId` from the CALLER's verified scope. Two cannot,
 * and they are pinned here because an un-pinned inherited stamp is how a tenant
 * boundary quietly stops covering the rows a product generates on its own:
 *
 *   1. `recurringTasks.processDueTasks` — a CRON. It has no caller and
 *      therefore no scope of its own, so the tenant is carried on the
 *      `recurringTasks` row (stamped when a verified caller created the
 *      schedule) and inherited by every task the schedule emits. Without this,
 *      every cron-generated task would be untenanted — and since absence now
 *      grants nothing, invisible to the very org that registered the schedule.
 *      A single unstamped schedule is a RECURRING source of invisible rows.
 *
 *   2. `missionTemplates.instantiateTemplateIntoMission` — the child tasks
 *      inherit the TARGET MISSION's tenant rather than the caller's. Inheriting
 *      is derivation, not inference: a task is a child of exactly one mission,
 *      and the authorization check upstream has already refused any caller whose
 *      scope does not own that mission. Re-deriving from the caller would split
 *      parent from children whenever master instantiated into a client mission.
 *
 * Both are proved under an ORDINARY org identity, never master.
 */

import { convexTest } from "convex-test";
import { describe, expect, test } from "vitest";
import { api, internal } from "../_generated/api";
import schema from "../schema";

const modules = Object.fromEntries(
	Object.entries(import.meta.glob("../**/*.ts")).filter(
		([path]) => !path.includes("ragSync") && !path.includes("backfill"),
	),
);

const createT = () => convexTest(schema, modules);
const SHARED = "eta";

async function seedBothOrgs(t: ReturnType<typeof createT>) {
	await t.run(async (ctx) => {
		for (const slug of ["org-a", "org-b"]) {
			await ctx.db.insert("client_org_mapping", {
				clerkOrgSlug: slug,
				allowedOrchestrators: [SHARED],
				scopes: ["view-own-tasks", "view-own-missions"],
				displayName: slug,
				isActive: true,
				createdAt: Date.now(),
			});
		}
	});
}

const asOrg = (t: ReturnType<typeof createT>, slug: string) =>
	t.withIdentity({
		subject: `user-${slug}`,
		organizationId: slug,
	} as Parameters<typeof t.withIdentity>[0]);

describe("recurringTasks.processDueTasks — the cron inherits the schedule's tenant", () => {
	test("the schedule itself is stamped with its creator's verified org", async () => {
		const t = createT();
		await seedBothOrgs(t);

		const id = await asOrg(t, "org-a").mutation(api.recurringTasks.create, {
			title: "daily scan",
			assignedTo: SHARED,
			priority: "medium",
			cronExpression: "0 9 * * *",
			createdBy: SHARED,
		});

		const row = await t.run(async (ctx) => ctx.db.get(id));
		expect(row?.orgId).toBe("org-a");
	});

	test("a task the cron generates carries the SCHEDULE's tenant, not nothing", async () => {
		const t = createT();
		await seedBothOrgs(t);

		const id = await asOrg(t, "org-a").mutation(api.recurringTasks.create, {
			title: "daily scan",
			assignedTo: SHARED,
			priority: "medium",
			cronExpression: "0 9 * * *",
			createdBy: SHARED,
		});
		// Make the schedule due without touching the clock.
		await t.run(async (ctx) => ctx.db.patch(id, { nextRunAt: 1 }));

		await t.mutation(internal.recurringTasks.processDueTasks, {});

		const generated = await t.run(async (ctx) =>
			ctx.db
				.query("tasks")
				.filter((q) => q.eq(q.field("title"), "daily scan"))
				.collect(),
		);
		expect(generated.length).toBeGreaterThan(0);
		for (const g of generated) expect(g.orgId).toBe("org-a");
	});

	test("LEAK POLE: org B cannot read a task generated by org A's schedule", async () => {
		const t = createT();
		await seedBothOrgs(t);

		const id = await asOrg(t, "org-a").mutation(api.recurringTasks.create, {
			title: "daily scan",
			assignedTo: SHARED,
			priority: "medium",
			cronExpression: "0 9 * * *",
			createdBy: SHARED,
		});
		await t.run(async (ctx) => ctx.db.patch(id, { nextRunAt: 1 }));
		await t.mutation(internal.recurringTasks.processDueTasks, {});

		const [generated] = await t.run(async (ctx) =>
			ctx.db
				.query("tasks")
				.filter((q) => q.eq(q.field("title"), "daily scan"))
				.collect(),
		);

		// Both rosters carry "eta", so only a real tenant stamp separates them.
		expect(
			await asOrg(t, "org-b").query(api.tasks.get, { taskId: generated._id }),
		).toBeNull();
		// WITHHELD-GRANT POLE: the owning org still reads it.
		expect(
			await asOrg(t, "org-a").query(api.tasks.get, { taskId: generated._id }),
		).not.toBeNull();
	});
});

describe("missionTemplates — instantiated child tasks inherit the MISSION's tenant", () => {
	async function seedTemplate(t: ReturnType<typeof createT>) {
		await t.run(async (ctx) => {
			await ctx.db.insert("missionTemplates", {
				name: "tpl",
				steps: [{ title: "step one", description: "d", assignedTo: SHARED }],
				isDefault: false,
				createdBy: SHARED,
				createdAt: Date.now(),
				updatedAt: Date.now(),
			});
		});
	}

	test("children carry the target mission's org, and org B cannot read them", async () => {
		const t = createT();
		await seedBothOrgs(t);
		await seedTemplate(t);

		const missionId = await asOrg(t, "org-a").mutation(api.missions.create, {
			name: "org-a mission",
			project: "p",
			status: "execute",
			priority: "medium",
			pilot: SHARED,
			agents: [],
			createdBy: SHARED,
		});

		const { taskIds } = await asOrg(t, "org-a").mutation(
			api.missionTemplates.instantiateTemplateIntoMission,
			{ templateName: "tpl", missionId, callerOrchestrator: SHARED },
		);
		expect(taskIds.length).toBeGreaterThan(0);

		// The stamp itself, read from the row.
		const stored = await t.run(async (ctx) =>
			Promise.all(taskIds.map((id) => ctx.db.get(id))),
		);
		for (const row of stored) expect(row?.orgId).toBe("org-a");

		// LEAK POLE / WITHHELD-GRANT POLE on the same row.
		expect(
			await asOrg(t, "org-b").query(api.tasks.get, { taskId: taskIds[0] }),
		).toBeNull();
		expect(
			await asOrg(t, "org-a").query(api.tasks.get, { taskId: taskIds[0] }),
		).not.toBeNull();
	});
});
