/// <reference types="vite/client" />
//
// tasks.list_tasks_exclude_cron.test.ts — PR-E TDD-RED phase
// ─────────────────────────────────────────────────────────────────────────────
//
// Tests for the `excludeAutoGenerated: boolean` filter arg on `tasks.list`.
// Mission k571gcctka8mq5jbkgpj0a0b2n892ctg — VP-MCP top level Bloc A.
// Task ref: k173zpgb9hgdp5jewtg5j9t549892gx1.
//
// Audit context: 152 cron-spawned tasks pollute Pi's list_tasks queue.
// Two detection signals (OR logic):
//   1. createdBy matches /^cron-/i   — explicit cron-spawned creator prefix
//   2. title    matches /^\/?check-messages$/i — synthetic schedule task titles
//
// Convention established by this PR (no prior convention in codebase):
//   - cron-source marker = createdBy starting with "cron-" (dash required;
//     "cronus" or bare "cron" must NOT be filtered — anchored ^cron- with dash).
//   - synthetic title = exact whole-string "/check-messages" or "check-messages"
//     (case-insensitive; "/check-messages and more" must NOT be filtered).
//
// RED STRATEGY:
//   Tests T2–T7 call api.tasks.list with `excludeAutoGenerated` (unknown arg).
//   convex-test throws "Validator error: Unexpected field `excludeAutoGenerated`".
//   Tests assert the POST-GREEN result shape directly — no try/catch — so the
//   thrown error propagates and fails the test naturally.
//   T1 is GREEN today (uses no new arg) — regression guard for cursor paging callers.
//
// ─────────────────────────────────────────────────────────────────────────────

import { convexTest } from "convex-test";
import { describe, expect, test } from "vitest";
import { api } from "../_generated/api";
import schema from "../schema";

// Exclude RAG/search/backfill modules (standard pattern in this test suite)
const modules = Object.fromEntries(
	Object.entries(import.meta.glob("../**/*.ts")).filter(
		([path]) =>
			!path.includes("ragSync") &&
			!path.includes("search") &&
			!path.includes("backfill"),
	),
);

// ─── Types ────────────────────────────────────────────────────────────────────

type TaskRow = Record<string, unknown>;

// ─── Seed helper ──────────────────────────────────────────────────────────────

interface TaskSeed {
	title: string;
	assignedTo: string;
	priority: "urgent" | "high" | "medium" | "low";
	status: "todo" | "in_progress" | "review" | "blocked" | "done";
	createdBy: string;
	createdAt: number;
	updatedAt: number;
	description?: string;
	project?: string;
}

function makeTask(overrides: Partial<TaskSeed> = {}): TaskSeed {
	const now = Date.now();
	return {
		title: overrides.title ?? "Real task",
		assignedTo: overrides.assignedTo ?? "pi",
		priority: overrides.priority ?? "medium",
		status: overrides.status ?? "todo",
		createdBy: overrides.createdBy ?? "pi",
		createdAt: now,
		updatedAt: now,
		...(overrides.description !== undefined ? { description: overrides.description } : {}),
		...(overrides.project !== undefined ? { project: overrides.project } : {}),
	};
}

// seedTaskRows is a ctx callback — pass directly to t.run(seedTaskRows).
// Avoids explicit ReturnType<typeof convexTest<typeof schema>> annotation
// which triggers TS2344/TS2345 when the schema generic fails the GenericSchema constraint.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function seedTaskRows(ctx: any): Promise<void> {
	// Real tasks — must NOT be filtered
	for (let i = 0; i < 10; i++) {
		await ctx.db.insert("tasks", makeTask({ title: `Real task ${i}`, createdBy: "pi" }) as never);
	}
	// Sigma tasks (non-cron orchestrator) — must NOT be filtered
	for (let i = 0; i < 5; i++) {
		await ctx.db.insert("tasks", makeTask({ title: `Sigma task ${i}`, createdBy: "sigma" }) as never);
	}

	// Cron-spawned tasks — MUST be filtered by excludeAutoGenerated=true
	// Signal 1: createdBy matches ^cron-
	await ctx.db.insert("tasks", makeTask({ title: "Scheduled sweep A", createdBy: "cron-sweeper" }) as never);
	await ctx.db.insert("tasks", makeTask({ title: "Scheduled sweep B", createdBy: "cron-bot" }) as never);
	await ctx.db.insert("tasks", makeTask({ title: "Scheduled task C", createdBy: "cron-daily" }) as never);

	// Signal 2: title matches ^/?check-messages$ exactly
	await ctx.db.insert("tasks", makeTask({ title: "/check-messages", createdBy: "scheduler" }) as never);
	await ctx.db.insert("tasks", makeTask({ title: "check-messages", createdBy: "scheduler" }) as never);

	// False-positive guard 1: "cronus" has no dash → NOT filtered
	await ctx.db.insert("tasks", makeTask({ title: "Cronus task", createdBy: "cronus" }) as never);

	// False-positive guard 2: bare "cron" with no dash → NOT filtered
	await ctx.db.insert("tasks", makeTask({ title: "Cron no-dash task", createdBy: "cron" }) as never);

	// False-positive guard 3: "Check messages" (space, not dash) → NOT filtered
	await ctx.db.insert("tasks", makeTask({ title: "Check messages", createdBy: "pi" }) as never);

	// False-positive guard 4: "/check-messages and more" → not exact match → NOT filtered
	await ctx.db.insert("tasks", makeTask({ title: "/check-messages and more", createdBy: "pi" }) as never);

	// Edge: cron task with specific assignedTo + non-todo status
	await ctx.db.insert("tasks", makeTask({
		title: "Cron poller task",
		createdBy: "cron-poller",
		status: "done",
		assignedTo: "eta",
	}) as never);
}

// ─── Helper: extract items from result (array or envelope) ───────────────────

function extractItems(result: unknown): TaskRow[] {
	if (Array.isArray(result)) return result as TaskRow[];
	if (result !== null && typeof result === "object") {
		const r = result as Record<string, unknown>;
		if (Array.isArray(r.items)) return r.items as TaskRow[];
	}
	return [];
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("tasks.list excludeAutoGenerated filter (PR-E RED)", () => {

	// ── T1: GREEN today — regression guard ────────────────────────────────────
	// Confirms existing list behavior unchanged when arg is omitted.
	// Uses fields="full" so createdBy is present in the projection.
	test("T1: excludeAutoGenerated omitted → ALL tasks returned including cron-spawned (regression guard)", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedTaskRows);

		const result = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, { limit: 50, fields: "full" });
		const items = extractItems(result);

		// Without any filter, cron-spawned tasks must be present
		const cronItems = items.filter(
			(r) => typeof r.createdBy === "string" && r.createdBy.startsWith("cron-"),
		);
		expect(cronItems.length).toBeGreaterThan(0);

		// Synthetic title tasks must also be present
		const syntheticItems = items.filter(
			(r) => typeof r.title === "string" && /^\/?check-messages$/i.test(r.title),
		);
		expect(syntheticItems.length).toBeGreaterThan(0);
	});

	// ── T2–T7: RED today ─────────────────────────────────────────────────────
	// These call api.tasks.list with excludeAutoGenerated (unknown arg).
	// convex-test throws "Validator error: Unexpected field `excludeAutoGenerated`"
	// and the test fails at the await — RED signal.
	// T-GREEN adds the arg to convex/tasks.ts:list and makes these pass.

	// T2: excludeAutoGenerated=false → same as omit; all tasks returned
	test("T2: excludeAutoGenerated=false → ALL tasks returned (same as omitting the arg)", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedTaskRows);

		// RED: throws "Validator error: Unexpected field `excludeAutoGenerated`" today
		const result = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			limit: 50,
			fields: "full",
			excludeAutoGenerated: false,
		});
		const items = extractItems(result);

		// false = no filtering → all seeded tasks present including cron-spawned
		const cronItems = items.filter(
			(r) => typeof r.createdBy === "string" && r.createdBy.startsWith("cron-"),
		);
		expect(cronItems.length).toBeGreaterThan(0);
	});

	// T3: excludeAutoGenerated=true filters createdBy matching ^cron-
	test("T3: excludeAutoGenerated=true → no task with createdBy matching /^cron-/ survives", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedTaskRows);

		// RED: throws today — arg unknown
		const result = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			limit: 50,
			fields: "full",
			excludeAutoGenerated: true,
		});
		const items = extractItems(result);

		// All cron-prefixed tasks must be absent from the filtered result
		const cronItems = items.filter(
			(r) => typeof r.createdBy === "string" && /^cron-/i.test(r.createdBy),
		);
		expect(cronItems).toHaveLength(0);

		// Real tasks must still be present
		const realItems = items.filter((r) => r.createdBy === "pi" || r.createdBy === "sigma");
		expect(realItems.length).toBeGreaterThan(0);
	});

	// T4: excludeAutoGenerated=true filters title matching ^/?check-messages$
	test("T4: excludeAutoGenerated=true → no task with title /^\\/check-messages$/i survives", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedTaskRows);

		// RED: throws today
		const result = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			limit: 50,
			fields: "full",
			excludeAutoGenerated: true,
		});
		const items = extractItems(result);

		// Exact-match synthetic title tasks must be absent
		const syntheticItems = items.filter(
			(r) => typeof r.title === "string" && /^\/?check-messages$/i.test(r.title),
		);
		expect(syntheticItems).toHaveLength(0);
	});

	// T5: False-positive guard — "cronus" and bare "cron" are NOT filtered
	test("T5: false-positive guard — createdBy='cron' (no dash) and 'cronus' survive the filter", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedTaskRows);

		// RED: throws today
		const result = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			limit: 50,
			fields: "full",
			excludeAutoGenerated: true,
		});
		const items = extractItems(result);

		// "cronus" — starts with "cron" but has no dash → must NOT be filtered
		const cronusItems = items.filter((r) => r.createdBy === "cronus");
		expect(cronusItems.length).toBeGreaterThan(0);

		// bare "cron" (no dash) → must NOT be filtered
		const cronNoDashItems = items.filter((r) => r.createdBy === "cron");
		expect(cronNoDashItems.length).toBeGreaterThan(0);
	});

	// T6: False-positive guard 2 — non-exact-match titles survive
	test("T6: false-positive guard — 'Check messages' (space) and '/check-messages and more' survive", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedTaskRows);

		// RED: throws today
		const result = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			limit: 50,
			fields: "full",
			excludeAutoGenerated: true,
		});
		const items = extractItems(result);

		// "Check messages" — space separator, different from "check-messages" → NOT filtered
		const checkSpace = items.filter((r) => r.title === "Check messages");
		expect(checkSpace.length).toBeGreaterThan(0);

		// "/check-messages and more" — trailing text → not exact match → NOT filtered
		const checkLong = items.filter((r) => r.title === "/check-messages and more");
		expect(checkLong.length).toBeGreaterThan(0);
	});

	// T7: Filter composes with assignedTo + limit; returns only pi tasks without cron entries
	test("T7: excludeAutoGenerated=true + assignedTo='pi' + limit=20 → only non-cron pi tasks", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedTaskRows);

		// RED: throws today
		const result = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			assignedTo: "pi",
			limit: 20,
			fields: "full",
			excludeAutoGenerated: true,
		});
		const items = extractItems(result);

		// Result is non-empty (real pi tasks exist)
		expect(items.length).toBeGreaterThan(0);

		// No cron-spawned task survives (filter must apply before assignedTo filter)
		const cronItems = items.filter(
			(r) => typeof r.createdBy === "string" && /^cron-/i.test(r.createdBy),
		);
		expect(cronItems).toHaveLength(0);

		// Every returned task is assigned to "pi"
		for (const item of items) {
			expect(item.assignedTo).toBe("pi");
		}
	});
});
