/// <reference types="vite/client" />
//
// tasks.bulk_complete.test.ts — PR-F TDD-RED phase
// ─────────────────────────────────────────────────────────────────────────────
//
// Tests for the `bulkComplete` mutation on the tasks module.
// Mission k571gcctka8mq5jbkgpj0a0b2n892ctg — VP-MCP top level Bloc A.
//
// RED STRATEGY:
//   T1–T7 call api.tasks.bulkComplete (does not yet exist).
//   convex-test throws "Could not find public function for 'tasks:bulkComplete'"
//   (or equivalent "is not a function" / validator error) — the thrown error
//   propagates and fails the test naturally. No try/catch — raw RED.
//
// Feature contract (to be implemented in T-GREEN):
//   bulkComplete({
//     filter: {
//       autoGeneratedOnly?: boolean;    // same cron-detection as excludeAutoGenerated
//       assignedTo?: string;            // optional additional narrowing
//       status?: string;               // default "todo" | open statuses
//     },
//     dryRun?: boolean;                // default true (safety)
//     completionNoteTemplate?: string; // optional, {{day}} placeholder
//     callerOrchestrator?: string;     // RBAC gate
//   }) → {
//     count: number;
//     sampleIds: Id<"tasks">[];
//     bulkRunId: string;               // evidence token
//     executedAt?: number;             // only on dryRun=false
//   }
//
// Cron-detection signals (same contract as PR-E excludeAutoGenerated):
//   1. createdBy matches /^cron-/i  (dash required — "cronus"/"cron" pass through)
//   2. title    matches /^\/?check-messages$/i  (exact whole-string match)
//
// ─────────────────────────────────────────────────────────────────────────────

import { convexTest } from "convex-test";
import { describe, expect, test } from "vitest";
import { api } from "../_generated/api";
import schema from "../schema";

// Exclude RAG/search/backfill modules (standard pattern in this test suite)
const modules = Object.fromEntries(
	Object.entries(import.meta.glob("../**/*.ts")).filter(
		([path]) =>
			!path.includes("ragSync") &&
			!path.includes("search") &&
			!path.includes("backfill"),
	),
);

// ─── Types ────────────────────────────────────────────────────────────────────

type TaskSeed = {
	title: string;
	assignedTo: string;
	priority: "urgent" | "high" | "medium" | "low";
	status: "todo" | "in_progress" | "review" | "blocked" | "done";
	createdBy: string;
	createdAt: number;
	updatedAt: number;
	description?: string;
	project?: string;
};

// ─── Seed helpers ─────────────────────────────────────────────────────────────

function makeTask(overrides: Partial<TaskSeed> = {}): TaskSeed {
	const now = Date.now();
	return {
		title: overrides.title ?? "Real task",
		assignedTo: overrides.assignedTo ?? "pi",
		priority: overrides.priority ?? "medium",
		status: overrides.status ?? "todo",
		createdBy: overrides.createdBy ?? "pi",
		createdAt: now,
		updatedAt: now,
		...(overrides.description !== undefined ? { description: overrides.description } : {}),
		...(overrides.project !== undefined ? { project: overrides.project } : {}),
	};
}

/**
 * seedCronSpamAndReal — seeds 50 cron-spam tasks + 5 real tasks.
 * Strategy B (PR-E): pass directly to t.run(seedCronSpamAndReal).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function seedCronSpamAndReal(ctx: any): Promise<void> {
	// 50 cron-spawned tasks via createdBy pattern
	for (let i = 0; i < 40; i++) {
		await ctx.db.insert(
			"tasks",
			makeTask({ title: `/check-messages run ${i}`, createdBy: "cron-checker" }) as never,
		);
	}
	// 10 more via title pattern (exact match)
	for (let i = 0; i < 5; i++) {
		await ctx.db.insert(
			"tasks",
			makeTask({ title: "/check-messages", createdBy: "scheduler" }) as never,
		);
	}
	for (let i = 0; i < 5; i++) {
		await ctx.db.insert(
			"tasks",
			makeTask({ title: "check-messages", createdBy: "scheduler" }) as never,
		);
	}

	// 5 real tasks — must NOT be touched
	for (let i = 0; i < 5; i++) {
		await ctx.db.insert(
			"tasks",
			makeTask({ title: `Real task ${i}`, createdBy: "pi", assignedTo: "pi" }) as never,
		);
	}
}

/**
 * seedSmallMix — seeds a small set for compositional tests.
 * eslint-disable-next-line @typescript-eslint/no-explicit-any
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function seedSmallMix(ctx: any): Promise<void> {
	// Cron tasks
	for (let i = 0; i < 3; i++) {
		await ctx.db.insert(
			"tasks",
			makeTask({ title: `Scheduled sweep ${i}`, createdBy: "cron-sweeper" }) as never,
		);
	}
	await ctx.db.insert(
		"tasks",
		makeTask({ title: "/check-messages", createdBy: "scheduler" }) as never,
	);

	// Real tasks assigned to different orchestrators
	await ctx.db.insert(
		"tasks",
		makeTask({ title: "Sigma feature", createdBy: "sigma", assignedTo: "sigma" }) as never,
	);
	await ctx.db.insert(
		"tasks",
		makeTask({ title: "Pi task", createdBy: "pi", assignedTo: "pi" }) as never,
	);
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("tasks.bulkComplete mutation (PR-F RED)", () => {

	// ── T1: 50 cron tasks closed, 5 real tasks untouched ─────────────────────
	// RED: api.tasks.bulkComplete does not exist → throws on call.
	test("T1: dryRun=false + autoGeneratedOnly → 50 cron tasks closed, 5 real tasks untouched", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedCronSpamAndReal);

		// RED: throws "Could not find public function for 'tasks:bulkComplete'"
		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			dryRun: false,
			callerOrchestrator: "system",
		});

		// Closed 50 cron tasks
		expect(result.count).toBe(50);

		// Real tasks still open
		const remaining = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, {
			limit: 50,
			fields: "full",
			excludeAutoGenerated: false,
		});
		const items = Array.isArray(remaining) ? remaining : (remaining as { items: unknown[] }).items ?? [];
		const realOpen = (items as Array<Record<string, unknown>>).filter(
			(r) => r.createdBy === "pi" && r.status !== "done",
		);
		expect(realOpen).toHaveLength(5);
	});

	// ── T2: dryRun=true returns preview, mutates nothing ─────────────────────
	test("T2: dryRun=true → returns {count, sampleIds[]} preview without mutating any task", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedCronSpamAndReal);

		// Count before
		const before = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, { limit: 100, fields: "lite" });
		const beforeItems = Array.isArray(before) ? before : (before as { items: unknown[] }).items ?? [];
		const beforeDone = (beforeItems as Array<Record<string, unknown>>).filter(
			(r) => r.status === "done",
		).length;

		// RED: throws today
		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			dryRun: true,
			callerOrchestrator: "system",
		});

		// Returns preview shape
		expect(typeof result.count).toBe("number");
		expect(result.count).toBeGreaterThan(0);
		expect(Array.isArray(result.sampleIds)).toBe(true);

		// No tasks mutated — done count unchanged
		const after = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, { limit: 100, fields: "lite" });
		const afterItems = Array.isArray(after) ? after : (after as { items: unknown[] }).items ?? [];
		const afterDone = (afterItems as Array<Record<string, unknown>>).filter(
			(r) => r.status === "done",
		).length;
		expect(afterDone).toBe(beforeDone);
	});

	// ── T3: completionNoteTemplate with {{day}} placeholder ──────────────────
	test("T3: completionNoteTemplate with {{day}} placeholder is interpolated per task", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedSmallMix);

		// RED: throws today
		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			dryRun: false,
			completionNoteTemplate: "bulk-cleanup: cron-spam day {{day}}",
			callerOrchestrator: "system",
		});

		expect(result.count).toBeGreaterThan(0);

		// Check completionNote on one closed task — must not contain literal "{{day}}"
		const taskId = result.sampleIds[0];
		if (taskId !== undefined) {
			// eslint-disable-next-line @typescript-eslint/no-explicit-any
			const task = await t.run(async (ctx: any) => {
				return await ctx.db.get(taskId);
			});
			expect(task).not.toBeNull();
			if (task !== null) {
				expect(typeof (task as Record<string, unknown>).completionNote).toBe("string");
				expect((task as Record<string, unknown>).completionNote).not.toContain("{{day}}");
				expect((task as Record<string, unknown>).completionNote).toContain("bulk-cleanup: cron-spam day");
			}
		}
	});

	// ── T4: default dryRun=true safety — omitting dryRun must NOT mutate ─────
	test("T4: default dryRun=true safety — calling without explicit dryRun must NOT mutate any task", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedCronSpamAndReal);

		const before = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, { limit: 100, fields: "lite" });
		const beforeItems = Array.isArray(before) ? before : (before as { items: unknown[] }).items ?? [];
		const beforeDone = (beforeItems as Array<Record<string, unknown>>).filter(
			(r) => r.status === "done",
		).length;

		// RED: throws today — and when implemented, no dryRun arg → defaults to true → no mutation
		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			// dryRun intentionally omitted — must default to true
			callerOrchestrator: "system",
		});

		// Returns preview, count > 0
		expect(result.count).toBeGreaterThan(0);

		// State unchanged
		const after = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, { limit: 100, fields: "lite" });
		const afterItems = Array.isArray(after) ? after : (after as { items: unknown[] }).items ?? [];
		const afterDone = (afterItems as Array<Record<string, unknown>>).filter(
			(r) => r.status === "done",
		).length;
		expect(afterDone).toBe(beforeDone);
	});

	// ── T5: cron contract identical to PR-E excludeAutoGenerated ─────────────
	// Signal 1: /^cron-/i with dash. Signal 2: /^\/?check-messages$/i exact.
	test("T5: filter respects same cron contract as PR-E — /^cron-/i OR /^\\/?check-messages$/i", async () => {
		const t = convexTest(schema, modules);

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		await t.run(async (ctx: any) => {
			// Should be caught (cron-prefixed)
			await ctx.db.insert("tasks", makeTask({ title: "daily sweep", createdBy: "cron-daily" }) as never);
			await ctx.db.insert("tasks", makeTask({ title: "bot run", createdBy: "cron-bot" }) as never);

			// Should be caught (exact title match)
			await ctx.db.insert("tasks", makeTask({ title: "/check-messages", createdBy: "sched" }) as never);
			await ctx.db.insert("tasks", makeTask({ title: "check-messages", createdBy: "sched" }) as never);

			// Should NOT be caught (no dash after cron)
			await ctx.db.insert("tasks", makeTask({ title: "cronus task", createdBy: "cronus" }) as never);
			await ctx.db.insert("tasks", makeTask({ title: "bare cron task", createdBy: "cron" }) as never);

			// Should NOT be caught (non-exact title)
			await ctx.db.insert("tasks", makeTask({ title: "Check messages today", createdBy: "pi" }) as never);
			await ctx.db.insert("tasks", makeTask({ title: "/check-messages and more", createdBy: "pi" }) as never);
		});

		// RED: throws today
		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			dryRun: false,
			callerOrchestrator: "system",
		});

		// Exactly 4 tasks caught: cron-daily, cron-bot, /check-messages, check-messages
		expect(result.count).toBe(4);

		// False-positive guard: cronus, cron (no dash), non-exact titles still open
		const allTasks = await t.withIdentity({ subject: "test-service-account-user-id" }).query(api.tasks.list, { limit: 50, fields: "full" });
		const allItems = Array.isArray(allTasks)
			? allTasks
			: (allTasks as { items: unknown[] }).items ?? [];
		const surviving = (allItems as Array<Record<string, unknown>>).filter(
			(r) => r.status !== "done",
		);
		const survivingCreatedBys = surviving.map((r) => r.createdBy as string);
		expect(survivingCreatedBys).toContain("cronus");
		expect(survivingCreatedBys).toContain("cron"); // bare "cron", no dash
		// Titles "Check messages today" and "/check-messages and more" survive
		const survivingTitles = surviving.map((r) => r.title as string);
		expect(survivingTitles).toContain("Check messages today");
		expect(survivingTitles).toContain("/check-messages and more");
	});

	// ── T6: each closed task's completionNote has evidence token ─────────────
	// Day-76 evidence-bound doctrine: completionNote must contain bulkRunId
	// and executedAt (ms timestamp) so the close is auditable / verifiable.
	test("T6: each closed task completionNote contains bulkRunId + executedAt proof token (Day-76 evidence-bound)", async () => {
		const t = convexTest(schema, modules);
		await t.run(seedSmallMix);

		// RED: throws today
		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			dryRun: false,
			callerOrchestrator: "system",
		});

		// Result must carry bulkRunId + executedAt
		expect(typeof result.bulkRunId).toBe("string");
		expect(result.bulkRunId.length).toBeGreaterThan(0);
		expect(typeof result.executedAt).toBe("number");

		// Each closed task's completionNote embeds both proof tokens
		for (const taskId of result.sampleIds) {
			// eslint-disable-next-line @typescript-eslint/no-explicit-any
			const task = await t.run(async (ctx: any) => ctx.db.get(taskId));
			expect(task).not.toBeNull();
			if (task !== null) {
				const note = (task as Record<string, unknown>).completionNote as string | undefined;
				expect(typeof note).toBe("string");
				// Must contain the bulkRunId token
				expect(note).toContain(result.bulkRunId);
				// Must contain a numeric timestamp (executedAt as string substring)
				expect(note).toMatch(/\d{10,}/); // at least 10-digit epoch ms
			}
		}
	});

	// ── T8: 501 cron tasks exceed the 500 hard cap — Day 163 (Pi) ────────────
	// Was: throws BULK_HARD_CAP_EXCEEDED with an un-followable "narrow your
	// filter" (both filter fields were already at their narrowest). Now: the
	// live path drains the first cap-sized batch, labels the result
	// `remaining: true`, and a second call with the SAME filter closes the
	// rest — because the first batch is now "done" and drops out of the
	// non-done scan.
	test("T8: 501 cron-spam tasks — live path drains cap batch + labels remaining, second call finishes the rest", async () => {
		const t = convexTest(schema, modules);

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		await t.run(async (ctx: any) => {
			for (let i = 0; i < 501; i++) {
				await ctx.db.insert(
					"tasks",
					makeTask({ title: `/check-messages run ${i}`, createdBy: "cron-checker" }) as never,
				);
			}
		});

		const first = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(first.count).toBe(500);
		expect(first.cappedAt).toBe(500);
		expect(first.remaining).toBe(true);

		const second = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true },
			dryRun: false,
			callerOrchestrator: "system",
		});
		expect(second.count).toBe(1);
		expect(second.remaining).toBeUndefined();
	});

	// ── T9: BULK_FILTER_TOO_BROAD — empty filter is rejected ─────────────────
	test("T9: BULK_FILTER_TOO_BROAD — calling with an empty filter throws regardless of dryRun", async () => {
		const t = convexTest(schema, modules);

		await expect(
			t.mutation(api.tasks.bulkComplete, {
				filter: {},
				dryRun: true,
			}),
		).rejects.toThrow(/BULK_FILTER_TOO_BROAD/);
	});

	// ── T10: BULK_CALLER_REQUIRED — dryRun=false without callerOrchestrator ──
	test("T10: BULK_CALLER_REQUIRED — dryRun=false without callerOrchestrator throws", async () => {
		const t = convexTest(schema, modules);

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		await t.run(async (ctx: any) => {
			for (let i = 0; i < 5; i++) {
				await ctx.db.insert(
					"tasks",
					makeTask({ title: "/check-messages", createdBy: "cron-checker" }) as never,
				);
			}
		});

		await expect(
			t.mutation(api.tasks.bulkComplete, {
				filter: { autoGeneratedOnly: true },
				dryRun: false,
				// callerOrchestrator intentionally omitted
			}),
		).rejects.toThrow(/BULK_CALLER_REQUIRED/);
	});

	// ── T11: assignedTo scoping — only tasks for the given assignee are closed ─
	test("T11: assignedTo scoping — only alpha-assigned cron tasks are closed, beta tasks untouched", async () => {
		const t = convexTest(schema, modules);

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		await t.run(async (ctx: any) => {
			// 5 cron tasks assigned to alpha
			for (let i = 0; i < 5; i++) {
				await ctx.db.insert(
					"tasks",
					makeTask({ title: `/check-messages alpha ${i}`, createdBy: "cron-checker", assignedTo: "alpha" }) as never,
				);
			}
			// 5 cron tasks assigned to beta
			for (let i = 0; i < 5; i++) {
				await ctx.db.insert(
					"tasks",
					makeTask({ title: `/check-messages beta ${i}`, createdBy: "cron-checker", assignedTo: "beta" }) as never,
				);
			}
		});

		const result = await t.mutation(api.tasks.bulkComplete, {
			filter: { autoGeneratedOnly: true, assignedTo: "alpha" },
			dryRun: false,
			callerOrchestrator: "alpha",
		});

		// Only the 5 alpha tasks are closed
		expect(result.count).toBe(5);

		// Beta tasks must still be open
		/* eslint-disable @typescript-eslint/no-explicit-any */
		const betaStillOpen = await t.run(async (ctx: any) => {
			return await ctx.db
				.query("tasks")
				.withIndex("by_assignee", (q: any) => q.eq("assignedTo", "beta"))
				.filter((q: any) => q.neq(q.field("status"), "done"))
				.collect();
		});
		/* eslint-enable @typescript-eslint/no-explicit-any */
		expect(betaStillOpen).toHaveLength(5);
	});

	// ── T7: callerOrchestrator RBAC — non-system caller rejected ─────────────
	// bulkComplete is a privileged write. A non-creator/non-system orchestrator
	// MUST be rejected with an RBAC_DENIED ConvexError.
	// We seed tasks owned by "pi" and call as "sigma".
	//
	// RED: throws "no such export" today (wrong error message).
	// T-GREEN: must throw with message matching /RBAC_DENIED/i.
	test("T7: callerOrchestrator RBAC — non-creator/non-assignee orchestrator is rejected with RBAC_DENIED", async () => {
		const t = convexTest(schema, modules);

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		await t.run(async (ctx: any) => {
			// Seed cron tasks created+assigned by "pi" — sigma did not create/assign them
			await ctx.db.insert(
				"tasks",
				makeTask({ title: "/check-messages", createdBy: "pi", assignedTo: "pi" }) as never,
			);
			await ctx.db.insert(
				"tasks",
				makeTask({ title: "cron job task", createdBy: "cron-checker", assignedTo: "pi" }) as never,
			);
		});

		// RED: throws "no such export" which does NOT match /RBAC_DENIED/i → test fails.
		// T-GREEN: mutation exists, throws ConvexError with "RBAC_DENIED" in message.
		await expect(
			t.mutation(api.tasks.bulkComplete, {
				filter: { autoGeneratedOnly: true },
				dryRun: false,
				callerOrchestrator: "sigma", // sigma did not create nor own these tasks
			}),
		).rejects.toThrow(/RBAC_DENIED/i);
	});
});
