// Stub for tsc — real file generated by `npx convex dev` when host mounts this component.
// Provides typed `api`, `internal`, and `components` references for this component's functions.
import type { FunctionReference } from "convex/server";

// Internal schedulable functions referenced by tasksV1.ts
interface GithubCommentsInternal {
  postComment: FunctionReference<"action", "internal">;
}

interface RagSyncInternal {
  addFixPatternRagEntry: FunctionReference<"action", "internal">;
}

// Internal mutation for recurringTasksV1.processDueTasks
interface RecurringTasksInternal {
  processDueTasks: FunctionReference<"mutation", "internal">;
}

export declare const api: {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
};

export declare const internal: {
  githubComments: GithubCommentsInternal;
  ragSync: RagSyncInternal;
  recurringTasks: RecurringTasksInternal;
};

// Component shape (populated at mount time)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const components: Record<string, any>;
