// Stub for tsc — real file generated by `npx convex dev` when host mounts this component.
// Re-exports from convex/server + derives DataModel from this component's schema.
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNames,
} from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema.js";

export type TableNames = TableNamesInDataModel<DataModel>;

export type Doc<TableName extends TableNames> = DocumentByName<
  DataModel,
  TableName
>;

export type Id<TableName extends TableNames | SystemTableNames> =
  GenericId<TableName>;

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
