// Stub for tsc — real file generated by `npx convex dev` when host mounts this component.
// Binds generic function builders to this component's DataModel.
import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
  httpActionGeneric,
  type QueryBuilder,
  type MutationBuilder,
  type ActionBuilder,
  type HttpActionBuilder,
  type GenericQueryCtx,
  type GenericMutationCtx,
  type GenericActionCtx,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export const query: QueryBuilder<DataModel, "public"> =
  queryGeneric as unknown as QueryBuilder<DataModel, "public">;

export const internalQuery: QueryBuilder<DataModel, "internal"> =
  internalQueryGeneric as unknown as QueryBuilder<DataModel, "internal">;

export const mutation: MutationBuilder<DataModel, "public"> =
  mutationGeneric as unknown as MutationBuilder<DataModel, "public">;

export const internalMutation: MutationBuilder<DataModel, "internal"> =
  internalMutationGeneric as unknown as MutationBuilder<DataModel, "internal">;

export const action: ActionBuilder<DataModel, "public"> =
  actionGeneric as unknown as ActionBuilder<DataModel, "public">;

export const internalAction: ActionBuilder<DataModel, "internal"> =
  internalActionGeneric as unknown as ActionBuilder<DataModel, "internal">;

export const httpAction: HttpActionBuilder =
  httpActionGeneric as unknown as HttpActionBuilder;

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
